/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type { EventSummary, ReflectionGet } from "../../models";

export const getGetReflectionResponseEventSummaryMock = (overrideResponse: Partial<EventSummary> = {}): EventSummary => ({
	...{ id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
	...overrideResponse,
});

export const getGetReflectionResponseMock = (overrideResponse: Partial<Extract<ReflectionGet, object>> = {}): ReflectionGet => ({
	id: faker.string.uuid(),
	event: faker.helpers.arrayElement([faker.helpers.arrayElement([null, { ...getGetReflectionResponseEventSummaryMock() }]), undefined]),
	date: faker.date.past().toISOString().slice(0, 19) + "Z",
	positive: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	negative: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	improvement: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	...overrideResponse,
});

export const getListReflectionsResponseEventSummaryMock = (overrideResponse: Partial<EventSummary> = {}): EventSummary => ({
	...{ id: faker.string.uuid(), name: faker.string.alpha({ length: { min: 10, max: 20 } }) },
	...overrideResponse,
});

export const getListReflectionsResponseMock = (): ReflectionGet[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
		id: faker.string.uuid(),
		event: faker.helpers.arrayElement([faker.helpers.arrayElement([null, { ...getListReflectionsResponseEventSummaryMock() }]), undefined]),
		date: faker.date.past().toISOString().slice(0, 19) + "Z",
		positive: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
		negative: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
		improvement: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
	}));

export const getCreateReflectionResponseMock = (): string => faker.word.sample();

export const getReflectionPromptDataResponseMock = (): string => faker.word.sample();
