/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { cFetch } from "../../../other/cfetch";
import type { DeleteReflectionParams, GetReflectionParams, ReflectionCreate, ReflectionGet } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getReflectionResponse200 = {
	data: ReflectionGet;
	status: 200;
};

export type getReflectionResponseSuccess = getReflectionResponse200 & {
	headers: Headers;
};

export type getReflectionResponse = getReflectionResponseSuccess;

export const getGetReflectionUrl = (params?: GetReflectionParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get?${stringifiedParams}`
		: `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`;
};

export const getReflection = async (params?: GetReflectionParams, options?: RequestInit): Promise<getReflectionResponse> => {
	return cFetch<getReflectionResponse>(getGetReflectionUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGetReflectionKey = (params?: GetReflectionParams) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`, ...(params ? [params] : [])] as const;

export type GetReflectionQueryResult = NonNullable<Awaited<ReturnType<typeof getReflection>>>;

export const useGetReflection = <TError = unknown>(
	params?: GetReflectionParams,
	options?: {
		swr?: SWRConfiguration<Awaited<ReturnType<typeof getReflection>>, TError> & { swrKey?: Key; enabled?: boolean };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetReflectionKey(params) : null));
	const swrFn = () => getReflection(params, requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type listReflectionsResponse200 = {
	data: ReflectionGet[];
	status: 200;
};

export type listReflectionsResponseSuccess = listReflectionsResponse200 & {
	headers: Headers;
};

export type listReflectionsResponse = listReflectionsResponseSuccess;

export const getListReflectionsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`;
};

export const listReflections = async (options?: RequestInit): Promise<listReflectionsResponse> => {
	return cFetch<listReflectionsResponse>(getListReflectionsUrl(), {
		...options,
		method: "GET",
	});
};

export const getListReflectionsKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`] as const;

export type ListReflectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listReflections>>>;

export const useListReflections = <TError = unknown>(options?: {
	swr?: SWRConfiguration<Awaited<ReturnType<typeof listReflections>>, TError> & { swrKey?: Key; enabled?: boolean };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getListReflectionsKey() : null));
	const swrFn = () => listReflections(requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type createReflectionResponse200 = {
	data: string;
	status: 200;
};

export type createReflectionResponseSuccess = createReflectionResponse200 & {
	headers: Headers;
};

export type createReflectionResponse = createReflectionResponseSuccess;

export const getCreateReflectionUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Create`;
};

export const createReflection = async (reflectionCreate: ReflectionCreate, options?: RequestInit): Promise<createReflectionResponse> => {
	return cFetch<createReflectionResponse>(getCreateReflectionUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(reflectionCreate),
	});
};

export const getCreateReflectionMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: ReflectionCreate }) => {
		return createReflection(arg, options);
	};
};
export const getCreateReflectionMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Create`] as const;

export type CreateReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof createReflection>>>;

export const useCreateReflection = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof createReflection>>,
		TError,
		Key,
		ReflectionCreate,
		Awaited<ReturnType<typeof createReflection>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getCreateReflectionMutationKey();
	const swrFn = getCreateReflectionMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type updateReflectionResponse200 = {
	data: void;
	status: 200;
};

export type updateReflectionResponseSuccess = updateReflectionResponse200 & {
	headers: Headers;
};

export type updateReflectionResponse = updateReflectionResponseSuccess;

export const getUpdateReflectionUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Update`;
};

export const updateReflection = async (options?: RequestInit): Promise<updateReflectionResponse> => {
	return cFetch<updateReflectionResponse>(getUpdateReflectionUrl(), {
		...options,
		method: "POST",
	});
};

export const getUpdateReflectionMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return updateReflection(options);
	};
};
export const getUpdateReflectionMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Update`] as const;

export type UpdateReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateReflection>>>;

export const useUpdateReflection = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof updateReflection>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof updateReflection>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getUpdateReflectionMutationKey();
	const swrFn = getUpdateReflectionMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type deleteReflectionResponse200 = {
	data: void;
	status: 200;
};

export type deleteReflectionResponseSuccess = deleteReflectionResponse200 & {
	headers: Headers;
};

export type deleteReflectionResponse = deleteReflectionResponseSuccess;

export const getDeleteReflectionUrl = (params?: DeleteReflectionParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete?${stringifiedParams}`
		: `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete`;
};

export const deleteReflection = async (params?: DeleteReflectionParams, options?: RequestInit): Promise<deleteReflectionResponse> => {
	return cFetch<deleteReflectionResponse>(getDeleteReflectionUrl(params), {
		...options,
		method: "POST",
	});
};

export const getDeleteReflectionMutationFetcher = (params?: DeleteReflectionParams, options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return deleteReflection(params, options);
	};
};
export const getDeleteReflectionMutationKey = (params?: DeleteReflectionParams) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete`, ...(params ? [params] : [])] as const;

export type DeleteReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReflection>>>;

export const useDeleteReflection = <TError = unknown>(
	params?: DeleteReflectionParams,
	options?: {
		swr?: SWRMutationConfiguration<
			Awaited<ReturnType<typeof deleteReflection>>,
			TError,
			Key,
			Arguments,
			Awaited<ReturnType<typeof deleteReflection>>
		> & { swrKey?: string };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getDeleteReflectionMutationKey(params);
	const swrFn = getDeleteReflectionMutationFetcher(params, requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type reflectionPromptDataResponse200 = {
	data: string;
	status: 200;
};

export type reflectionPromptDataResponseSuccess = reflectionPromptDataResponse200 & {
	headers: Headers;
};

export type reflectionPromptDataResponse = reflectionPromptDataResponseSuccess;

export const getReflectionPromptDataUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/PromptData`;
};

export const reflectionPromptData = async (options?: RequestInit): Promise<reflectionPromptDataResponse> => {
	return cFetch<reflectionPromptDataResponse>(getReflectionPromptDataUrl(), {
		...options,
		method: "POST",
	});
};

export const getReflectionPromptDataMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return reflectionPromptData(options);
	};
};
export const getReflectionPromptDataMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/PromptData`] as const;

export type ReflectionPromptDataMutationResult = NonNullable<Awaited<ReturnType<typeof reflectionPromptData>>>;

export const useReflectionPromptData = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof reflectionPromptData>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof reflectionPromptData>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getReflectionPromptDataMutationKey();
	const swrFn = getReflectionPromptDataMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type reflectionPromptResponse200 = {
	data: void;
	status: 200;
};

export type reflectionPromptResponseSuccess = reflectionPromptResponse200 & {
	headers: Headers;
};

export type reflectionPromptResponse = reflectionPromptResponseSuccess;

export const getReflectionPromptUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Prompt`;
};

export const reflectionPrompt = async (options?: RequestInit): Promise<reflectionPromptResponse> => {
	return cFetch<reflectionPromptResponse>(getReflectionPromptUrl(), {
		...options,
		method: "POST",
	});
};

export const getReflectionPromptMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return reflectionPrompt(options);
	};
};
export const getReflectionPromptMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Prompt`] as const;

export type ReflectionPromptMutationResult = NonNullable<Awaited<ReturnType<typeof reflectionPrompt>>>;

export const useReflectionPrompt = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof reflectionPrompt>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof reflectionPrompt>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getReflectionPromptMutationKey();
	const swrFn = getReflectionPromptMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
