/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";

import type { ReflectionGet } from "../../models";

export const getGetReflectionResponseMock = (overrideResponse: Partial<Extract<ReflectionGet, object>> = {}): ReflectionGet => ({
	id: faker.string.uuid(),
	eventId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
	date: faker.date.past().toISOString().slice(0, 19) + "Z",
	positive: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	negative: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	improvement: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.string.alpha({ length: { min: 10, max: 20 } }),
	),
	...overrideResponse,
});

export const getListReflectionsResponseMock = (): ReflectionGet[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
		id: faker.string.uuid(),
		eventId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
		date: faker.date.past().toISOString().slice(0, 19) + "Z",
		positive: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
		negative: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
		improvement: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
			faker.string.alpha({ length: { min: 10, max: 20 } }),
		),
	}));

export const getCreateReflectionResponseMock = (): string => faker.word.sample();

export const getReflectionPromptDataResponseMock = (): string => faker.word.sample();

export const getGetReflectionMockHandler = (
	overrideResponse?: ReflectionGet | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReflectionGet> | ReflectionGet),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/Reflection/Get",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetReflectionResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getListReflectionsMockHandler = (
	overrideResponse?: ReflectionGet[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReflectionGet[]> | ReflectionGet[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/Reflection/List",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListReflectionsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getCreateReflectionMockHandler = (
	overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Reflection/Create",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateReflectionResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUpdateReflectionMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Reflection/Update",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getDeleteReflectionMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Reflection/Delete",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getReflectionPromptDataMockHandler = (
	overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Reflection/PromptData",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getReflectionPromptDataResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getReflectionPromptMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Reflection/Prompt",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};
export const getReflectionMock = () => [
	getGetReflectionMockHandler(),
	getListReflectionsMockHandler(),
	getCreateReflectionMockHandler(),
	getUpdateReflectionMockHandler(),
	getDeleteReflectionMockHandler(),
	getReflectionPromptDataMockHandler(),
	getReflectionPromptMockHandler(),
];
