/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import { cFetch } from "../../../other/cfetch";
import type { DeleteReflectionParams, GetReflectionParams, ReflectionCreate, ReflectionGet } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getReflectionResponse200 = {
	data: ReflectionGet;
	status: 200;
};

export type getReflectionResponseSuccess = getReflectionResponse200 & {
	headers: Headers;
};

export type getReflectionResponse = getReflectionResponseSuccess;

export const getGetReflectionUrl = (params?: GetReflectionParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get?${stringifiedParams}`
		: `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`;
};

export const getReflection = async (params?: GetReflectionParams, options?: RequestInit): Promise<getReflectionResponse> => {
	return cFetch<getReflectionResponse>(getGetReflectionUrl(params), {
		...options,
		method: "GET",
	});
};

export const getGetReflectionQueryKey = (params?: GetReflectionParams) => {
	return [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`, ...(params ? [params] : [])] as const;
};

export const getGetReflectionQueryOptions = <TData = Awaited<ReturnType<typeof getReflection>>, TError = unknown>(
	params?: GetReflectionParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetReflectionQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getReflection>>> = ({ signal }) => getReflection(params, { signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetReflectionQueryResult = NonNullable<Awaited<ReturnType<typeof getReflection>>>;
export type GetReflectionQueryError = unknown;

export function useGetReflection<TData = Awaited<ReturnType<typeof getReflection>>, TError = unknown>(
	params: undefined | GetReflectionParams,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData>> &
			Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getReflection>>, TError, Awaited<ReturnType<typeof getReflection>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReflection<TData = Awaited<ReturnType<typeof getReflection>>, TError = unknown>(
	params?: GetReflectionParams,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData>> &
			Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getReflection>>, TError, Awaited<ReturnType<typeof getReflection>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetReflection<TData = Awaited<ReturnType<typeof getReflection>>, TError = unknown>(
	params?: GetReflectionParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetReflection<TData = Awaited<ReturnType<typeof getReflection>>, TError = unknown>(
	params?: GetReflectionParams,
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getReflection>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetReflectionQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type listReflectionsResponse200 = {
	data: ReflectionGet[];
	status: 200;
};

export type listReflectionsResponseSuccess = listReflectionsResponse200 & {
	headers: Headers;
};

export type listReflectionsResponse = listReflectionsResponseSuccess;

export const getListReflectionsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`;
};

export const listReflections = async (options?: RequestInit): Promise<listReflectionsResponse> => {
	return cFetch<listReflectionsResponse>(getListReflectionsUrl(), {
		...options,
		method: "GET",
	});
};

export const getListReflectionsQueryKey = () => {
	return [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`] as const;
};

export const getListReflectionsQueryOptions = <TData = Awaited<ReturnType<typeof listReflections>>, TError = unknown>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData>>;
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListReflectionsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listReflections>>> = ({ signal }) => listReflections({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ListReflectionsQueryResult = NonNullable<Awaited<ReturnType<typeof listReflections>>>;
export type ListReflectionsQueryError = unknown;

export function useListReflections<TData = Awaited<ReturnType<typeof listReflections>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<Awaited<ReturnType<typeof listReflections>>, TError, Awaited<ReturnType<typeof listReflections>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListReflections<TData = Awaited<ReturnType<typeof listReflections>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<Awaited<ReturnType<typeof listReflections>>, TError, Awaited<ReturnType<typeof listReflections>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListReflections<TData = Awaited<ReturnType<typeof listReflections>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListReflections<TData = Awaited<ReturnType<typeof listReflections>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listReflections>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListReflectionsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export type createReflectionResponse200 = {
	data: string;
	status: 200;
};

export type createReflectionResponseSuccess = createReflectionResponse200 & {
	headers: Headers;
};

export type createReflectionResponse = createReflectionResponseSuccess;

export const getCreateReflectionUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Create`;
};

export const createReflection = async (reflectionCreate: ReflectionCreate, options?: RequestInit): Promise<createReflectionResponse> => {
	return cFetch<createReflectionResponse>(getCreateReflectionUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(reflectionCreate),
	});
};

export const getCreateReflectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof createReflection>>, TError, { data: ReflectionCreate }, TContext>;
	request?: SecondParameter<typeof cFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof createReflection>>, TError, { data: ReflectionCreate }, TContext> => {
	const mutationKey = ["createReflection"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReflection>>, { data: ReflectionCreate }> = (props) => {
		const { data } = props ?? {};

		return createReflection(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof createReflection>>>;
export type CreateReflectionMutationBody = ReflectionCreate;
export type CreateReflectionMutationError = unknown;

export const useCreateReflection = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createReflection>>, TError, { data: ReflectionCreate }, TContext>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createReflection>>, TError, { data: ReflectionCreate }, TContext> => {
	return useMutation(getCreateReflectionMutationOptions(options), queryClient);
};
export type updateReflectionResponse200 = {
	data: void;
	status: 200;
};

export type updateReflectionResponseSuccess = updateReflectionResponse200 & {
	headers: Headers;
};

export type updateReflectionResponse = updateReflectionResponseSuccess;

export const getUpdateReflectionUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Update`;
};

export const updateReflection = async (options?: RequestInit): Promise<updateReflectionResponse> => {
	return cFetch<updateReflectionResponse>(getUpdateReflectionUrl(), {
		...options,
		method: "POST",
	});
};

export const getUpdateReflectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateReflection>>, TError, void, TContext>;
	request?: SecondParameter<typeof cFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof updateReflection>>, TError, void, TContext> => {
	const mutationKey = ["updateReflection"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReflection>>, void> = () => {
		return updateReflection(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateReflection>>>;

export type UpdateReflectionMutationError = unknown;

export const useUpdateReflection = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateReflection>>, TError, void, TContext>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateReflection>>, TError, void, TContext> => {
	return useMutation(getUpdateReflectionMutationOptions(options), queryClient);
};
export type deleteReflectionResponse200 = {
	data: void;
	status: 200;
};

export type deleteReflectionResponseSuccess = deleteReflectionResponse200 & {
	headers: Headers;
};

export type deleteReflectionResponse = deleteReflectionResponseSuccess;

export const getDeleteReflectionUrl = (params?: DeleteReflectionParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete?${stringifiedParams}`
		: `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete`;
};

export const deleteReflection = async (params?: DeleteReflectionParams, options?: RequestInit): Promise<deleteReflectionResponse> => {
	return cFetch<deleteReflectionResponse>(getDeleteReflectionUrl(params), {
		...options,
		method: "POST",
	});
};

export const getDeleteReflectionMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteReflection>>, TError, { params?: DeleteReflectionParams }, TContext>;
	request?: SecondParameter<typeof cFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteReflection>>, TError, { params?: DeleteReflectionParams }, TContext> => {
	const mutationKey = ["deleteReflection"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReflection>>, { params?: DeleteReflectionParams }> = (props) => {
		const { params } = props ?? {};

		return deleteReflection(params, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteReflectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReflection>>>;

export type DeleteReflectionMutationError = unknown;

export const useDeleteReflection = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteReflection>>, TError, { params?: DeleteReflectionParams }, TContext>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteReflection>>, TError, { params?: DeleteReflectionParams }, TContext> => {
	return useMutation(getDeleteReflectionMutationOptions(options), queryClient);
};
export type reflectionPromptDataResponse200 = {
	data: string;
	status: 200;
};

export type reflectionPromptDataResponseSuccess = reflectionPromptDataResponse200 & {
	headers: Headers;
};

export type reflectionPromptDataResponse = reflectionPromptDataResponseSuccess;

export const getReflectionPromptDataUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/PromptData`;
};

export const reflectionPromptData = async (options?: RequestInit): Promise<reflectionPromptDataResponse> => {
	return cFetch<reflectionPromptDataResponse>(getReflectionPromptDataUrl(), {
		...options,
		method: "POST",
	});
};

export const getReflectionPromptDataMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof reflectionPromptData>>, TError, void, TContext>;
	request?: SecondParameter<typeof cFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof reflectionPromptData>>, TError, void, TContext> => {
	const mutationKey = ["reflectionPromptData"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof reflectionPromptData>>, void> = () => {
		return reflectionPromptData(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReflectionPromptDataMutationResult = NonNullable<Awaited<ReturnType<typeof reflectionPromptData>>>;

export type ReflectionPromptDataMutationError = unknown;

export const useReflectionPromptData = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof reflectionPromptData>>, TError, void, TContext>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof reflectionPromptData>>, TError, void, TContext> => {
	return useMutation(getReflectionPromptDataMutationOptions(options), queryClient);
};
export type reflectionPromptResponse200 = {
	data: void;
	status: 200;
};

export type reflectionPromptResponseSuccess = reflectionPromptResponse200 & {
	headers: Headers;
};

export type reflectionPromptResponse = reflectionPromptResponseSuccess;

export const getReflectionPromptUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Prompt`;
};

export const reflectionPrompt = async (options?: RequestInit): Promise<reflectionPromptResponse> => {
	return cFetch<reflectionPromptResponse>(getReflectionPromptUrl(), {
		...options,
		method: "POST",
	});
};

export const getReflectionPromptMutationOptions = <TError = unknown, TContext = unknown>(options?: {
	mutation?: UseMutationOptions<Awaited<ReturnType<typeof reflectionPrompt>>, TError, void, TContext>;
	request?: SecondParameter<typeof cFetch>;
}): UseMutationOptions<Awaited<ReturnType<typeof reflectionPrompt>>, TError, void, TContext> => {
	const mutationKey = ["reflectionPrompt"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof reflectionPrompt>>, void> = () => {
		return reflectionPrompt(requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type ReflectionPromptMutationResult = NonNullable<Awaited<ReturnType<typeof reflectionPrompt>>>;

export type ReflectionPromptMutationError = unknown;

export const useReflectionPrompt = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof reflectionPrompt>>, TError, void, TContext>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof reflectionPrompt>>, TError, void, TContext> => {
	return useMutation(getReflectionPromptMutationOptions(options), queryClient);
};
