---

- name: Configure Patroni
  ansible.builtin.template:
    src: templates/config.yml.j2
    dest: /etc/patroni/config.yml
    owner: root
    group: postgres
    mode: "0640"
  no_log: true

- name: Start Patroni
  ansible.builtin.service:
    name: patroni
    enabled: true
    state: started
