/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	InvalidateOptions,
	MutationFunction,
	MutationFunctionContext,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cFetch } from "../../../other/cfetch";
import type {
	BearingCreate,
	BearingUpdate,
	DeleteGoalParams,
	GoalStats,
	MovementCreate,
	MovementUpdate,
	NorthStarCreate,
	NorthStarGet,
	NorthStarUpdate,
} from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type listGoalsResponse200 = {
	data: NorthStarGet[];
	status: 200;
};

export type listGoalsResponseSuccess = listGoalsResponse200 & {
	headers: Headers;
};

export type listGoalsResponse = listGoalsResponseSuccess;

export const getListGoalsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/List`;
};

export const listGoals = async (options?: RequestInit): Promise<listGoalsResponse> => {
	return cFetch<listGoalsResponse>(getListGoalsUrl(), {
		...options,
		method: "GET",
	});
};

export const getListGoalsQueryKey = () => {
	return ["listGoals"] as const;
};

export const getListGoalsQueryOptions = <TData = Awaited<ReturnType<typeof listGoals>>, TError = unknown>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData>>;
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListGoalsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listGoals>>> = ({ signal }) => listGoals({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ListGoalsQueryResult = NonNullable<Awaited<ReturnType<typeof listGoals>>>;
export type ListGoalsQueryError = unknown;

export function useListGoals<TData = Awaited<ReturnType<typeof listGoals>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData>> &
			Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof listGoals>>, TError, Awaited<ReturnType<typeof listGoals>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListGoals<TData = Awaited<ReturnType<typeof listGoals>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData>> &
			Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof listGoals>>, TError, Awaited<ReturnType<typeof listGoals>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListGoals<TData = Awaited<ReturnType<typeof listGoals>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListGoals<TData = Awaited<ReturnType<typeof listGoals>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listGoals>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListGoalsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateListGoals = async (queryClient: QueryClient, options?: InvalidateOptions): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() }, options);

	return queryClient;
};

export type goalStatsResponse200 = {
	data: GoalStats;
	status: 200;
};

export type goalStatsResponseSuccess = goalStatsResponse200 & {
	headers: Headers;
};

export type goalStatsResponse = goalStatsResponseSuccess;

export const getGoalStatsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/Stats`;
};

export const goalStats = async (options?: RequestInit): Promise<goalStatsResponse> => {
	return cFetch<goalStatsResponse>(getGoalStatsUrl(), {
		...options,
		method: "GET",
	});
};

export const getGoalStatsQueryKey = () => {
	return ["goalStats"] as const;
};

export const getGoalStatsQueryOptions = <TData = Awaited<ReturnType<typeof goalStats>>, TError = unknown>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData>>;
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGoalStatsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof goalStats>>> = ({ signal }) => goalStats({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GoalStatsQueryResult = NonNullable<Awaited<ReturnType<typeof goalStats>>>;
export type GoalStatsQueryError = unknown;

export function useGoalStats<TData = Awaited<ReturnType<typeof goalStats>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData>> &
			Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof goalStats>>, TError, Awaited<ReturnType<typeof goalStats>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGoalStats<TData = Awaited<ReturnType<typeof goalStats>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData>> &
			Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof goalStats>>, TError, Awaited<ReturnType<typeof goalStats>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGoalStats<TData = Awaited<ReturnType<typeof goalStats>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGoalStats<TData = Awaited<ReturnType<typeof goalStats>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof goalStats>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGoalStatsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateGoalStats = async (queryClient: QueryClient, options?: InvalidateOptions): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() }, options);

	return queryClient;
};

export type createNorthStarResponse200 = {
	data: void;
	status: 200;
};

export type createNorthStarResponseSuccess = createNorthStarResponse200 & {
	headers: Headers;
};

export type createNorthStarResponse = createNorthStarResponseSuccess;

export const getCreateNorthStarUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/CreateNorthStar`;
};

export const createNorthStar = async (northStarCreate: NorthStarCreate, options?: RequestInit): Promise<createNorthStarResponse> => {
	return cFetch<createNorthStarResponse>(getCreateNorthStarUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(northStarCreate),
	});
};

export const getCreateNorthStarMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createNorthStar>>, TError, { data: NorthStarCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof createNorthStar>>, TError, { data: NorthStarCreate }, TContext> => {
	const mutationKey = ["createNorthStar"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNorthStar>>, { data: NorthStarCreate }> = (props) => {
		const { data } = props ?? {};

		return createNorthStar(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof createNorthStar>>,
		variables: { data: NorthStarCreate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type CreateNorthStarMutationResult = NonNullable<Awaited<ReturnType<typeof createNorthStar>>>;
export type CreateNorthStarMutationBody = NorthStarCreate;
export type CreateNorthStarMutationError = unknown;

export const useCreateNorthStar = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createNorthStar>>, TError, { data: NorthStarCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createNorthStar>>, TError, { data: NorthStarCreate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getCreateNorthStarMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type createBearingResponse200 = {
	data: void;
	status: 200;
};

export type createBearingResponseSuccess = createBearingResponse200 & {
	headers: Headers;
};

export type createBearingResponse = createBearingResponseSuccess;

export const getCreateBearingUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/CreateBearing`;
};

export const createBearing = async (bearingCreate: BearingCreate, options?: RequestInit): Promise<createBearingResponse> => {
	return cFetch<createBearingResponse>(getCreateBearingUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(bearingCreate),
	});
};

export const getCreateBearingMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createBearing>>, TError, { data: BearingCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof createBearing>>, TError, { data: BearingCreate }, TContext> => {
	const mutationKey = ["createBearing"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBearing>>, { data: BearingCreate }> = (props) => {
		const { data } = props ?? {};

		return createBearing(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof createBearing>>,
		variables: { data: BearingCreate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type CreateBearingMutationResult = NonNullable<Awaited<ReturnType<typeof createBearing>>>;
export type CreateBearingMutationBody = BearingCreate;
export type CreateBearingMutationError = unknown;

export const useCreateBearing = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createBearing>>, TError, { data: BearingCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createBearing>>, TError, { data: BearingCreate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getCreateBearingMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type createMovementResponse200 = {
	data: void;
	status: 200;
};

export type createMovementResponseSuccess = createMovementResponse200 & {
	headers: Headers;
};

export type createMovementResponse = createMovementResponseSuccess;

export const getCreateMovementUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/CreateMovement`;
};

export const createMovement = async (movementCreate: MovementCreate, options?: RequestInit): Promise<createMovementResponse> => {
	return cFetch<createMovementResponse>(getCreateMovementUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(movementCreate),
	});
};

export const getCreateMovementMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createMovement>>, TError, { data: MovementCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof createMovement>>, TError, { data: MovementCreate }, TContext> => {
	const mutationKey = ["createMovement"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMovement>>, { data: MovementCreate }> = (props) => {
		const { data } = props ?? {};

		return createMovement(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof createMovement>>,
		variables: { data: MovementCreate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type CreateMovementMutationResult = NonNullable<Awaited<ReturnType<typeof createMovement>>>;
export type CreateMovementMutationBody = MovementCreate;
export type CreateMovementMutationError = unknown;

export const useCreateMovement = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createMovement>>, TError, { data: MovementCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createMovement>>, TError, { data: MovementCreate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getCreateMovementMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type updateNorthStarResponse200 = {
	data: void;
	status: 200;
};

export type updateNorthStarResponseSuccess = updateNorthStarResponse200 & {
	headers: Headers;
};

export type updateNorthStarResponse = updateNorthStarResponseSuccess;

export const getUpdateNorthStarUrl = (id: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/UpdateNorthStar/${id}`;
};

export const updateNorthStar = async (id: string, northStarUpdate: NorthStarUpdate, options?: RequestInit): Promise<updateNorthStarResponse> => {
	return cFetch<updateNorthStarResponse>(getUpdateNorthStarUrl(id), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(northStarUpdate),
	});
};

export const getUpdateNorthStarMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateNorthStar>>, TError, { id: string; data: NorthStarUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof updateNorthStar>>, TError, { id: string; data: NorthStarUpdate }, TContext> => {
	const mutationKey = ["updateNorthStar"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateNorthStar>>, { id: string; data: NorthStarUpdate }> = (props) => {
		const { id, data } = props ?? {};

		return updateNorthStar(id, data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof updateNorthStar>>,
		variables: { id: string; data: NorthStarUpdate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateNorthStarMutationResult = NonNullable<Awaited<ReturnType<typeof updateNorthStar>>>;
export type UpdateNorthStarMutationBody = NorthStarUpdate;
export type UpdateNorthStarMutationError = unknown;

export const useUpdateNorthStar = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateNorthStar>>, TError, { id: string; data: NorthStarUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateNorthStar>>, TError, { id: string; data: NorthStarUpdate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getUpdateNorthStarMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type updateBearingResponse200 = {
	data: void;
	status: 200;
};

export type updateBearingResponseSuccess = updateBearingResponse200 & {
	headers: Headers;
};

export type updateBearingResponse = updateBearingResponseSuccess;

export const getUpdateBearingUrl = (id: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/UpdateBearing/${id}`;
};

export const updateBearing = async (id: string, bearingUpdate: BearingUpdate, options?: RequestInit): Promise<updateBearingResponse> => {
	return cFetch<updateBearingResponse>(getUpdateBearingUrl(id), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(bearingUpdate),
	});
};

export const getUpdateBearingMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateBearing>>, TError, { id: string; data: BearingUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof updateBearing>>, TError, { id: string; data: BearingUpdate }, TContext> => {
	const mutationKey = ["updateBearing"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBearing>>, { id: string; data: BearingUpdate }> = (props) => {
		const { id, data } = props ?? {};

		return updateBearing(id, data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof updateBearing>>,
		variables: { id: string; data: BearingUpdate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateBearingMutationResult = NonNullable<Awaited<ReturnType<typeof updateBearing>>>;
export type UpdateBearingMutationBody = BearingUpdate;
export type UpdateBearingMutationError = unknown;

export const useUpdateBearing = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateBearing>>, TError, { id: string; data: BearingUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateBearing>>, TError, { id: string; data: BearingUpdate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getUpdateBearingMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type updateMovementResponse200 = {
	data: void;
	status: 200;
};

export type updateMovementResponseSuccess = updateMovementResponse200 & {
	headers: Headers;
};

export type updateMovementResponse = updateMovementResponseSuccess;

export const getUpdateMovementUrl = (id: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Goal/UpdateMovement/${id}`;
};

export const updateMovement = async (id: string, movementUpdate: MovementUpdate, options?: RequestInit): Promise<updateMovementResponse> => {
	return cFetch<updateMovementResponse>(getUpdateMovementUrl(id), {
		...options,
		method: "PATCH",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(movementUpdate),
	});
};

export const getUpdateMovementMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateMovement>>, TError, { id: string; data: MovementUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof updateMovement>>, TError, { id: string; data: MovementUpdate }, TContext> => {
	const mutationKey = ["updateMovement"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMovement>>, { id: string; data: MovementUpdate }> = (props) => {
		const { id, data } = props ?? {};

		return updateMovement(id, data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof updateMovement>>,
		variables: { id: string; data: MovementUpdate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateMovementMutationResult = NonNullable<Awaited<ReturnType<typeof updateMovement>>>;
export type UpdateMovementMutationBody = MovementUpdate;
export type UpdateMovementMutationError = unknown;

export const useUpdateMovement = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateMovement>>, TError, { id: string; data: MovementUpdate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateMovement>>, TError, { id: string; data: MovementUpdate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getUpdateMovementMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type deleteGoalResponse200 = {
	data: void;
	status: 200;
};

export type deleteGoalResponseSuccess = deleteGoalResponse200 & {
	headers: Headers;
};

export type deleteGoalResponse = deleteGoalResponseSuccess;

export const getDeleteGoalUrl = (params?: DeleteGoalParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `${import.meta.env.VITE_API_ORIGIN}/api/Goal/Delete?${stringifiedParams}`
		: `${import.meta.env.VITE_API_ORIGIN}/api/Goal/Delete`;
};

export const deleteGoal = async (params?: DeleteGoalParams, options?: RequestInit): Promise<deleteGoalResponse> => {
	return cFetch<deleteGoalResponse>(getDeleteGoalUrl(params), {
		...options,
		method: "POST",
	});
};

export const getDeleteGoalMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteGoal>>, TError, { params?: DeleteGoalParams }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof deleteGoal>>, TError, { params?: DeleteGoalParams }, TContext> => {
	const mutationKey = ["deleteGoal"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGoal>>, { params?: DeleteGoalParams }> = (props) => {
		const { params } = props ?? {};

		return deleteGoal(params, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof deleteGoal>>,
		variables: { params?: DeleteGoalParams },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListGoalsQueryKey() });
			queryClient.invalidateQueries({ queryKey: getGoalStatsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type DeleteGoalMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGoal>>>;

export type DeleteGoalMutationError = unknown;

export const useDeleteGoal = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteGoal>>, TError, { params?: DeleteGoalParams }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteGoal>>, TError, { params?: DeleteGoalParams }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getDeleteGoalMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
