/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { GoalStats, NorthStarGet } from "../../models";
import { GoalImportance } from "../../models";

export const getListGoalsResponseMock = (): NorthStarGet[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
		description: faker.string.alpha({ length: { min: 10, max: 200 } }),
		importance: faker.helpers.arrayElement(Object.values(GoalImportance)),
		justification: faker.string.alpha({ length: { min: 10, max: 5000 } }),
		bearings: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
			northStarId: faker.string.uuid(),
			description: faker.string.alpha({ length: { min: 10, max: 5000 } }),
			justification: faker.string.alpha({ length: { min: 10, max: 5000 } }),
			strengths: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]), undefined]),
			weaknesses: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]), undefined]),
			movements: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
				bearingId: faker.string.uuid(),
				difficulty: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]),
					undefined,
				]),
				motivationType: faker.helpers.arrayElement([
					faker.helpers.arrayElement([null, faker.helpers.arrayElement(["Carrot", "Stick"] as const)]),
					undefined,
				]),
				motivation: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]),
					undefined,
				]),
				triggers: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]), undefined]),
				temptations: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]),
					undefined,
				]),
				obstacles: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]),
					undefined,
				]),
				killConditions: faker.helpers.arrayElement([
					faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 5000 } }), null]),
					undefined,
				]),
				id: faker.string.uuid(),
				name: faker.string.alpha({ length: { min: 10, max: 200 } }),
			})),
			id: faker.string.uuid(),
			name: faker.string.alpha({ length: { min: 10, max: 200 } }),
		})),
		id: faker.string.uuid(),
		name: faker.string.alpha({ length: { min: 10, max: 200 } }),
	}));

export const getGoalStatsResponseMock = (overrideResponse: Partial<Extract<GoalStats, object>> = {}): GoalStats => ({
	northStarCount: faker.helpers.arrayElement([faker.number.int(), faker.helpers.fromRegExp("^-?(?:0|[1-9]\\d*)$")]),
	bearingCount: faker.helpers.arrayElement([faker.number.int(), faker.helpers.fromRegExp("^-?(?:0|[1-9]\\d*)$")]),
	movementCount: faker.helpers.arrayElement([faker.number.int(), faker.helpers.fromRegExp("^-?(?:0|[1-9]\\d*)$")]),
	...overrideResponse,
});
