---

service_certs:
  - name: etcd
    group: etcd
  - name: patroni
    group: postgres
  - name: postgres
    group: postgres

postgresql_version: 18
postgresql_app_user: app_user
postgresql_app_db: app_db
