---

accounts_groups:
  - name: ansible
    gid: 1002
    state: present
  - name: dev
    gid: 1003
    state: present

accounts_users:
  - name: ansible
    uid: 1002
    group: ansible
    sudo: "ALL=(ALL:ALL) NOPASSWD:ALL"
    ssh_key: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SSH_PUBLIC_KEY') }}"
    state: present
  - name: dev
    uid: 1003
    group: dev
    sudo: "ALL=(ALL:ALL) NOPASSWD:ALL"
    ssh_key: "{{ lookup('ansible.builtin.env', 'DEV_SSH_PUBLIC_KEY') }}"
    state: present
