---

- name: Run backend container
  community.docker.docker_container:
    name: backend
    image: "{{ backend_runtime_image }}"
    published_ports:
      - 80:8080
    env:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: "Server={{ hostnames.database }};Port={{ ports.haproxy_database }};Database={{ database.app_db }};User Id={{ database.app_user }};Password={{ dbproxy_runtime_password }}"
    restart_policy: always
    state: started
  no_log: true
