/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const postApiAuthSignUpBodyAccessCodeMin = 3;
export const postApiAuthSignUpBodyAccessCodeMax = 20;


export const postApiAuthSignUpBodyAccessCodeRegExp = new RegExp('^[a-zA-Z]+$');
export const postApiAuthSignUpBodyUsernameMin = 3;
export const postApiAuthSignUpBodyUsernameMax = 20;


export const postApiAuthSignUpBodyUsernameRegExp = new RegExp('^[a-zA-Z0-9]+$');
export const postApiAuthSignUpBodyEmailMax = 256;

export const postApiAuthSignUpBodyPasswordMin = 16;
export const postApiAuthSignUpBodyPasswordMax = 64;


export const postApiAuthSignUpBodyPasswordRegExp = new RegExp('^[a-zA-Z0-9]+$');


export const PostApiAuthSignUpBody = zod.object({
  "accessCode": zod.string().min(postApiAuthSignUpBodyAccessCodeMin).max(postApiAuthSignUpBodyAccessCodeMax).regex(postApiAuthSignUpBodyAccessCodeRegExp),
  "username": zod.string().min(postApiAuthSignUpBodyUsernameMin).max(postApiAuthSignUpBodyUsernameMax).regex(postApiAuthSignUpBodyUsernameRegExp),
  "email": zod.string().max(postApiAuthSignUpBodyEmailMax),
  "password": zod.string().min(postApiAuthSignUpBodyPasswordMin).max(postApiAuthSignUpBodyPasswordMax).regex(postApiAuthSignUpBodyPasswordRegExp),
  "termsOfService": zod.boolean()
})

export const postApiAuthSignInBodyUsernameMin = 3;
export const postApiAuthSignInBodyUsernameMax = 20;


export const postApiAuthSignInBodyUsernameRegExp = new RegExp('^[a-zA-Z0-9]+$');
export const postApiAuthSignInBodyPasswordMin = 16;
export const postApiAuthSignInBodyPasswordMax = 64;


export const postApiAuthSignInBodyPasswordRegExp = new RegExp('^[a-zA-Z0-9]+$');


export const PostApiAuthSignInBody = zod.object({
  "username": zod.string().min(postApiAuthSignInBodyUsernameMin).max(postApiAuthSignInBodyUsernameMax).regex(postApiAuthSignInBodyUsernameRegExp),
  "password": zod.string().min(postApiAuthSignInBodyPasswordMin).max(postApiAuthSignInBodyPasswordMax).regex(postApiAuthSignInBodyPasswordRegExp)
})

