/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  SigninForm,
  SignupForm
} from '../../models';






export type postApiAuthSignUpResponse200 = {
  data: string
  status: 200
}

export type postApiAuthSignUpResponseSuccess = (postApiAuthSignUpResponse200) & {
  headers: Headers;
};
;

export type postApiAuthSignUpResponse = (postApiAuthSignUpResponseSuccess)

export const getPostApiAuthSignUpUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`
}

export const postApiAuthSignUp = async (signupForm: SignupForm, options?: RequestInit): Promise<postApiAuthSignUpResponse> => {

  const res = await fetch(getPostApiAuthSignUpUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupForm,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthSignUpResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as postApiAuthSignUpResponse
}




export const getPostApiAuthSignUpMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: SignupForm }) => {
    return postApiAuthSignUp(arg, options);
  }
}
export const getPostApiAuthSignUpMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`] as const;

export type PostApiAuthSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthSignUp>>>

export const usePostApiAuthSignUp = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiAuthSignUp>>, TError, Key, SignupForm, Awaited<ReturnType<typeof postApiAuthSignUp>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiAuthSignUpMutationKey();
  const swrFn = getPostApiAuthSignUpMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiAuthSignInResponse200 = {
  data: string
  status: 200
}

export type postApiAuthSignInResponseSuccess = (postApiAuthSignInResponse200) & {
  headers: Headers;
};
;

export type postApiAuthSignInResponse = (postApiAuthSignInResponseSuccess)

export const getPostApiAuthSignInUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`
}

export const postApiAuthSignIn = async (signinForm: SigninForm, options?: RequestInit): Promise<postApiAuthSignInResponse> => {

  const res = await fetch(getPostApiAuthSignInUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signinForm,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthSignInResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as postApiAuthSignInResponse
}




export const getPostApiAuthSignInMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: SigninForm }) => {
    return postApiAuthSignIn(arg, options);
  }
}
export const getPostApiAuthSignInMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`] as const;

export type PostApiAuthSignInMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthSignIn>>>

export const usePostApiAuthSignIn = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiAuthSignIn>>, TError, Key, SigninForm, Awaited<ReturnType<typeof postApiAuthSignIn>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiAuthSignInMutationKey();
  const swrFn = getPostApiAuthSignInMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getApiAuthSignOutResponse200 = {
  data: void
  status: 200
}

export type getApiAuthSignOutResponseSuccess = (getApiAuthSignOutResponse200) & {
  headers: Headers;
};
;

export type getApiAuthSignOutResponse = (getApiAuthSignOutResponseSuccess)

export const getGetApiAuthSignOutUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`
}

export const getApiAuthSignOut = async ( options?: RequestInit): Promise<getApiAuthSignOutResponse> => {

  const res = await fetch(getGetApiAuthSignOutUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiAuthSignOutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as getApiAuthSignOutResponse
}




export const getGetApiAuthSignOutKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`] as const;

export type GetApiAuthSignOutQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthSignOut>>>

export const useGetApiAuthSignOut = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiAuthSignOut>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiAuthSignOutKey() : null);
  const swrFn = () => getApiAuthSignOut(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiAuthIsAuthenticatedResponse200 = {
  data: void
  status: 200
}

export type postApiAuthIsAuthenticatedResponseSuccess = (postApiAuthIsAuthenticatedResponse200) & {
  headers: Headers;
};
;

export type postApiAuthIsAuthenticatedResponse = (postApiAuthIsAuthenticatedResponseSuccess)

export const getPostApiAuthIsAuthenticatedUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`
}

export const postApiAuthIsAuthenticated = async ( options?: RequestInit): Promise<postApiAuthIsAuthenticatedResponse> => {

  const res = await fetch(getPostApiAuthIsAuthenticatedUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiAuthIsAuthenticatedResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiAuthIsAuthenticatedResponse
}




export const getPostApiAuthIsAuthenticatedMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiAuthIsAuthenticated(options);
  }
}
export const getPostApiAuthIsAuthenticatedMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`] as const;

export type PostApiAuthIsAuthenticatedMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthIsAuthenticated>>>

export const usePostApiAuthIsAuthenticated = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiAuthIsAuthenticated>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiAuthIsAuthenticated>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiAuthIsAuthenticatedMutationKey();
  const swrFn = getPostApiAuthIsAuthenticatedMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
