/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { cFetch } from "../../../other/cfetch";
import type { SigninForm, SignupForm } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type postApiAuthSignUpResponse200 = {
	data: string;
	status: 200;
};

export type postApiAuthSignUpResponseSuccess = postApiAuthSignUpResponse200 & {
	headers: Headers;
};

export type postApiAuthSignUpResponse = postApiAuthSignUpResponseSuccess;

export const getPostApiAuthSignUpUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`;
};

export const postApiAuthSignUp = async (signupForm: SignupForm, options?: RequestInit): Promise<postApiAuthSignUpResponse> => {
	return cFetch<postApiAuthSignUpResponse>(getPostApiAuthSignUpUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signupForm),
	});
};

export const getPostApiAuthSignUpMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: SignupForm }) => {
		return postApiAuthSignUp(arg, options);
	};
};
export const getPostApiAuthSignUpMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`] as const;

export type PostApiAuthSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthSignUp>>>;

export const usePostApiAuthSignUp = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiAuthSignUp>>,
		TError,
		Key,
		SignupForm,
		Awaited<ReturnType<typeof postApiAuthSignUp>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiAuthSignUpMutationKey();
	const swrFn = getPostApiAuthSignUpMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type postApiAuthSignInResponse200 = {
	data: string;
	status: 200;
};

export type postApiAuthSignInResponseSuccess = postApiAuthSignInResponse200 & {
	headers: Headers;
};

export type postApiAuthSignInResponse = postApiAuthSignInResponseSuccess;

export const getPostApiAuthSignInUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`;
};

export const postApiAuthSignIn = async (signinForm: SigninForm, options?: RequestInit): Promise<postApiAuthSignInResponse> => {
	return cFetch<postApiAuthSignInResponse>(getPostApiAuthSignInUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signinForm),
	});
};

export const getPostApiAuthSignInMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: SigninForm }) => {
		return postApiAuthSignIn(arg, options);
	};
};
export const getPostApiAuthSignInMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`] as const;

export type PostApiAuthSignInMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthSignIn>>>;

export const usePostApiAuthSignIn = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiAuthSignIn>>,
		TError,
		Key,
		SigninForm,
		Awaited<ReturnType<typeof postApiAuthSignIn>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiAuthSignInMutationKey();
	const swrFn = getPostApiAuthSignInMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type postApiAuthSignOutResponse204 = {
	data: void;
	status: 204;
};

export type postApiAuthSignOutResponseSuccess = postApiAuthSignOutResponse204 & {
	headers: Headers;
};

export type postApiAuthSignOutResponse = postApiAuthSignOutResponseSuccess;

export const getPostApiAuthSignOutUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`;
};

export const postApiAuthSignOut = async (options?: RequestInit): Promise<postApiAuthSignOutResponse> => {
	return cFetch<postApiAuthSignOutResponse>(getPostApiAuthSignOutUrl(), {
		...options,
		method: "POST",
	});
};

export const getPostApiAuthSignOutMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return postApiAuthSignOut(options);
	};
};
export const getPostApiAuthSignOutMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`] as const;

export type PostApiAuthSignOutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthSignOut>>>;

export const usePostApiAuthSignOut = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof postApiAuthSignOut>>,
		TError,
		Key,
		Arguments,
		Awaited<ReturnType<typeof postApiAuthSignOut>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getPostApiAuthSignOutMutationKey();
	const swrFn = getPostApiAuthSignOutMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type getApiAuthIsAuthenticatedResponse200 = {
	data: string;
	status: 200;
};

export type getApiAuthIsAuthenticatedResponseSuccess = getApiAuthIsAuthenticatedResponse200 & {
	headers: Headers;
};

export type getApiAuthIsAuthenticatedResponse = getApiAuthIsAuthenticatedResponseSuccess;

export const getGetApiAuthIsAuthenticatedUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`;
};

export const getApiAuthIsAuthenticated = async (options?: RequestInit): Promise<getApiAuthIsAuthenticatedResponse> => {
	return cFetch<getApiAuthIsAuthenticatedResponse>(getGetApiAuthIsAuthenticatedUrl(), {
		...options,
		method: "GET",
	});
};

export const getGetApiAuthIsAuthenticatedKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`] as const;

export type GetApiAuthIsAuthenticatedQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthIsAuthenticated>>>;

export const useGetApiAuthIsAuthenticated = <TError = unknown>(options?: {
	swr?: SWRConfiguration<Awaited<ReturnType<typeof getApiAuthIsAuthenticated>>, TError> & { swrKey?: Key; enabled?: boolean };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetApiAuthIsAuthenticatedKey() : null));
	const swrFn = () => getApiAuthIsAuthenticated(requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
