---

- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    system: true
    state: present

- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    group: etcd
    shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present

- name: Create etcd directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('etcd') }}"
    group: "{{ item.group | default('etcd') }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ etcd_config_dir }}"
      owner: root
      mode: "0750"
    - path: "{{ etcd_data_dir }}"
      mode: "0700"

- name: Download etcd
  ansible.builtin.get_url:
    url: https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz
    dest: /tmp/etcd.tar.gz
    owner: root
    group: root
    mode: "0644"
  notify:
    - Create etcd extraction directory
    - Extract etcd
    - Install etcd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add etcd service
  ansible.builtin.template:
    src: templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: "0755"
  notify: Reload systemd

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
