---

- name: Deploy to app at runtime
  become: true
  hosts: app
  vars_files:
    - ../shared/network.yaml
  roles:
    - ufw_runtime
    - migrations_runtime
    - pki_runtime
    - frontend_runtime
    - backend_runtime
