/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  EventGet
} from '../../models';


export const getGetApiEventGetResponseMock = (): EventGet[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.helpers.arrayElement([{type: faker.helpers.arrayElement(['onetime'] as const), id: faker.string.uuid(), movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]), title: faker.string.alpha({length: {min: 10, max: 200}}), start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'},{type: faker.helpers.arrayElement(['recurring'] as const), recurrence: {rrule: faker.string.alpha({length: {min: 10, max: 20}}), exDate: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}})))}, id: faker.string.uuid(), movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]), title: faker.string.alpha({length: {min: 10, max: 200}}), start: faker.date.past().toISOString().slice(0, 19) + 'Z', end: faker.date.past().toISOString().slice(0, 19) + 'Z'},]))))

export const getPostApiEventCreateOnetimeResponseMock = (): string => (faker.word.sample())

export const getPostApiEventCreateRecurringResponseMock = (): string => (faker.word.sample())


export const getGetApiEventGetMockHandler = (overrideResponse?: EventGet[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EventGet[]> | EventGet[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/Event/Get', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetApiEventGetResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiEventCreateOnetimeMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/api/Event/CreateOnetime', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiEventCreateOnetimeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiEventCreateRecurringMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/api/Event/CreateRecurring', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPostApiEventCreateRecurringResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostApiEventUpdateMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/Event/Update', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPostApiEventDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/api/Event/Delete', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getPutApiEventSetInstanceStateMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/api/Event/SetInstanceState', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getEventMock = () => [
  getGetApiEventGetMockHandler(),
  getPostApiEventCreateOnetimeMockHandler(),
  getPostApiEventCreateRecurringMockHandler(),
  getPostApiEventUpdateMockHandler(),
  getPostApiEventDeleteMockHandler(),
  getPutApiEventSetInstanceStateMockHandler()
]
