/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  EventGet,
  OnetimeEventCreate,
  RecurringEventCreate
} from '../../models';






export type getApiEventGetResponse200 = {
  data: EventGet[]
  status: 200
}

export type getApiEventGetResponseSuccess = (getApiEventGetResponse200) & {
  headers: Headers;
};
;

export type getApiEventGetResponse = (getApiEventGetResponseSuccess)

export const getGetApiEventGetUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Get`
}

export const getApiEventGet = async ( options?: RequestInit): Promise<getApiEventGetResponse> => {

  const res = await fetch(getGetApiEventGetUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiEventGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiEventGetResponse
}




export const getGetApiEventGetKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/Get`] as const;

export type GetApiEventGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEventGet>>>

export const useGetApiEventGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiEventGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiEventGetKey() : null);
  const swrFn = () => getApiEventGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiEventCreateOnetimeResponse200 = {
  data: string
  status: 200
}

export type postApiEventCreateOnetimeResponseSuccess = (postApiEventCreateOnetimeResponse200) & {
  headers: Headers;
};
;

export type postApiEventCreateOnetimeResponse = (postApiEventCreateOnetimeResponseSuccess)

export const getPostApiEventCreateOnetimeUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateOnetime`
}

export const postApiEventCreateOnetime = async (onetimeEventCreate: OnetimeEventCreate, options?: RequestInit): Promise<postApiEventCreateOnetimeResponse> => {

  const res = await fetch(getPostApiEventCreateOnetimeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      onetimeEventCreate,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiEventCreateOnetimeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiEventCreateOnetimeResponse
}




export const getPostApiEventCreateOnetimeMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: OnetimeEventCreate }) => {
    return postApiEventCreateOnetime(arg, options);
  }
}
export const getPostApiEventCreateOnetimeMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateOnetime`] as const;

export type PostApiEventCreateOnetimeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventCreateOnetime>>>

export const usePostApiEventCreateOnetime = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiEventCreateOnetime>>, TError, Key, OnetimeEventCreate, Awaited<ReturnType<typeof postApiEventCreateOnetime>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiEventCreateOnetimeMutationKey();
  const swrFn = getPostApiEventCreateOnetimeMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiEventCreateRecurringResponse200 = {
  data: string
  status: 200
}

export type postApiEventCreateRecurringResponseSuccess = (postApiEventCreateRecurringResponse200) & {
  headers: Headers;
};
;

export type postApiEventCreateRecurringResponse = (postApiEventCreateRecurringResponseSuccess)

export const getPostApiEventCreateRecurringUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateRecurring`
}

export const postApiEventCreateRecurring = async (recurringEventCreate: RecurringEventCreate, options?: RequestInit): Promise<postApiEventCreateRecurringResponse> => {

  const res = await fetch(getPostApiEventCreateRecurringUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recurringEventCreate,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiEventCreateRecurringResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiEventCreateRecurringResponse
}




export const getPostApiEventCreateRecurringMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: RecurringEventCreate }) => {
    return postApiEventCreateRecurring(arg, options);
  }
}
export const getPostApiEventCreateRecurringMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateRecurring`] as const;

export type PostApiEventCreateRecurringMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventCreateRecurring>>>

export const usePostApiEventCreateRecurring = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiEventCreateRecurring>>, TError, Key, RecurringEventCreate, Awaited<ReturnType<typeof postApiEventCreateRecurring>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiEventCreateRecurringMutationKey();
  const swrFn = getPostApiEventCreateRecurringMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiEventUpdateResponse200 = {
  data: void
  status: 200
}

export type postApiEventUpdateResponseSuccess = (postApiEventUpdateResponse200) & {
  headers: Headers;
};
;

export type postApiEventUpdateResponse = (postApiEventUpdateResponseSuccess)

export const getPostApiEventUpdateUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Update`
}

export const postApiEventUpdate = async ( options?: RequestInit): Promise<postApiEventUpdateResponse> => {

  const res = await fetch(getPostApiEventUpdateUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiEventUpdateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiEventUpdateResponse
}




export const getPostApiEventUpdateMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiEventUpdate(options);
  }
}
export const getPostApiEventUpdateMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/Update`] as const;

export type PostApiEventUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventUpdate>>>

export const usePostApiEventUpdate = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiEventUpdate>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiEventUpdate>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiEventUpdateMutationKey();
  const swrFn = getPostApiEventUpdateMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiEventDeleteResponse200 = {
  data: void
  status: 200
}

export type postApiEventDeleteResponseSuccess = (postApiEventDeleteResponse200) & {
  headers: Headers;
};
;

export type postApiEventDeleteResponse = (postApiEventDeleteResponseSuccess)

export const getPostApiEventDeleteUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Delete`
}

export const postApiEventDelete = async ( options?: RequestInit): Promise<postApiEventDeleteResponse> => {

  const res = await fetch(getPostApiEventDeleteUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiEventDeleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiEventDeleteResponse
}




export const getPostApiEventDeleteMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiEventDelete(options);
  }
}
export const getPostApiEventDeleteMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/Delete`] as const;

export type PostApiEventDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventDelete>>>

export const usePostApiEventDelete = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiEventDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiEventDelete>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiEventDeleteMutationKey();
  const swrFn = getPostApiEventDeleteMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
