/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { RequestHandlerOptions } from "msw";
import { HttpResponse, http } from "msw";
import type { EventGet, EventInstanceStateGet } from "../../models";
import { EventState } from "../../models";

export const getListEventsResponseMock = (): EventGet[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.helpers.arrayElement([
			{
				type: faker.helpers.arrayElement(["onetime"] as const),
				id: faker.string.uuid(),
				movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
				title: faker.string.alpha({ length: { min: 10, max: 200 } }),
				start: faker.date.past().toISOString().slice(0, 19) + "Z",
				end: faker.date.past().toISOString().slice(0, 19) + "Z",
			},
			{
				type: faker.helpers.arrayElement(["recurring"] as const),
				recurrence: {
					rrule: faker.string.alpha({ length: { min: 10, max: 20 } }),
					exDate: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
						faker.string.alpha({ length: { min: 10, max: 20 } }),
					),
				},
				id: faker.string.uuid(),
				movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
				title: faker.string.alpha({ length: { min: 10, max: 200 } }),
				start: faker.date.past().toISOString().slice(0, 19) + "Z",
				end: faker.date.past().toISOString().slice(0, 19) + "Z",
			},
		]),
	);

export const getCreateOnetimeResponseMock = (): string => faker.word.sample();

export const getCreateRecurringResponseMock = (): string => faker.word.sample();

export const getGetOnetimeInstanceStateResponseMock = (
	overrideResponse: Partial<Extract<EventInstanceStateGet, object>> = {},
): EventInstanceStateGet => ({ eventState: faker.helpers.arrayElement(Object.values(EventState)), ...overrideResponse });

export const getGetRecurringInstanceStateResponseMock = (
	overrideResponse: Partial<Extract<EventInstanceStateGet, object>> = {},
): EventInstanceStateGet => ({ eventState: faker.helpers.arrayElement(Object.values(EventState)), ...overrideResponse });

export const getListEventsMockHandler = (
	overrideResponse?: EventGet[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EventGet[]> | EventGet[]),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/Event/List",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getListEventsResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getCreateOnetimeMockHandler = (
	overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Event/CreateOnetime",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateOnetimeResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getCreateRecurringMockHandler = (
	overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Event/CreateRecurring",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getCreateRecurringResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getUpdateEventMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Event/Update",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getDeleteEventMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.post(
		"*/api/Event/Delete",
		async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getGetOnetimeInstanceStateMockHandler = (
	overrideResponse?:
		| EventInstanceStateGet
		| ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EventInstanceStateGet> | EventInstanceStateGet),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/Event/GetOnetimeInstanceState/onetime/:eventId",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetOnetimeInstanceStateResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getGetRecurringInstanceStateMockHandler = (
	overrideResponse?:
		| EventInstanceStateGet
		| ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<EventInstanceStateGet> | EventInstanceStateGet),
	options?: RequestHandlerOptions,
) => {
	return http.get(
		"*/api/Event/GetRecurringInstanceState/recurring/:eventId/:eventOccurence",
		async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
			return HttpResponse.json(
				overrideResponse !== undefined
					? typeof overrideResponse === "function"
						? await overrideResponse(info)
						: overrideResponse
					: getGetRecurringInstanceStateResponseMock(),
				{ status: 200 },
			);
		},
		options,
	);
};

export const getSetOnetimeInstanceStateMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/api/Event/SetOnetimeInstanceState/onetime/:eventId",
		async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};

export const getSetRecurringInstanceStateMockHandler = (
	overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void),
	options?: RequestHandlerOptions,
) => {
	return http.put(
		"*/api/Event/SetRecurringInstanceState/recurring/:eventId/:eventOccurence",
		async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
			if (typeof overrideResponse === "function") {
				await overrideResponse(info);
			}

			return new HttpResponse(null, { status: 200 });
		},
		options,
	);
};
export const getEventMock = () => [
	getListEventsMockHandler(),
	getCreateOnetimeMockHandler(),
	getCreateRecurringMockHandler(),
	getUpdateEventMockHandler(),
	getDeleteEventMockHandler(),
	getGetOnetimeInstanceStateMockHandler(),
	getGetRecurringInstanceStateMockHandler(),
	getSetOnetimeInstanceStateMockHandler(),
	getSetRecurringInstanceStateMockHandler(),
];
