/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";
import type { EventGet, EventInstanceStateGet } from "../../models";
import { EventState } from "../../models";

export const getListEventsResponseMock = (): EventGet[] =>
	Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
		faker.helpers.arrayElement([
			{
				type: faker.helpers.arrayElement(["onetime"] as const),
				id: faker.string.uuid(),
				movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
				title: faker.string.alpha({ length: { min: 10, max: 200 } }),
				start: faker.date.past().toISOString().slice(0, 19) + "Z",
				end: faker.date.past().toISOString().slice(0, 19) + "Z",
			},
			{
				type: faker.helpers.arrayElement(["recurring"] as const),
				recurrence: {
					rrule: faker.string.alpha({ length: { min: 10, max: 20 } }),
					exDate: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() =>
						faker.string.alpha({ length: { min: 10, max: 20 } }),
					),
				},
				id: faker.string.uuid(),
				movementId: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.uuid(), null]), undefined]),
				title: faker.string.alpha({ length: { min: 10, max: 200 } }),
				start: faker.date.past().toISOString().slice(0, 19) + "Z",
				end: faker.date.past().toISOString().slice(0, 19) + "Z",
			},
		]),
	);

export const getCreateOnetimeResponseMock = (): string => faker.word.sample();

export const getCreateRecurringResponseMock = (): string => faker.word.sample();

export const getGetOnetimeInstanceStateResponseMock = (
	overrideResponse: Partial<Extract<EventInstanceStateGet, object>> = {},
): EventInstanceStateGet => ({ eventState: faker.helpers.arrayElement(Object.values(EventState)), ...overrideResponse });

export const getGetRecurringInstanceStateResponseMock = (
	overrideResponse: Partial<Extract<EventInstanceStateGet, object>> = {},
): EventInstanceStateGet => ({ eventState: faker.helpers.arrayElement(Object.values(EventState)), ...overrideResponse });
