/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { cFetch } from "../../../other/cfetch";
import type { EventGet, EventInstanceStateGet, EventInstanceStateSet, OnetimeEventCreate, RecurringEventCreate } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type listEventsResponse200 = {
	data: EventGet[];
	status: 200;
};

export type listEventsResponseSuccess = listEventsResponse200 & {
	headers: Headers;
};

export type listEventsResponse = listEventsResponseSuccess;

export const getListEventsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/List`;
};

export const listEvents = async (options?: RequestInit): Promise<listEventsResponse> => {
	return cFetch<listEventsResponse>(getListEventsUrl(), {
		...options,
		method: "GET",
	});
};

export const getListEventsKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/List`] as const;

export type ListEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listEvents>>>;

export const useListEvents = <TError = unknown>(options?: {
	swr?: SWRConfiguration<Awaited<ReturnType<typeof listEvents>>, TError> & { swrKey?: Key; enabled?: boolean };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getListEventsKey() : null));
	const swrFn = () => listEvents(requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type createOnetimeResponse200 = {
	data: string;
	status: 200;
};

export type createOnetimeResponseSuccess = createOnetimeResponse200 & {
	headers: Headers;
};

export type createOnetimeResponse = createOnetimeResponseSuccess;

export const getCreateOnetimeUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateOnetime`;
};

export const createOnetime = async (onetimeEventCreate: OnetimeEventCreate, options?: RequestInit): Promise<createOnetimeResponse> => {
	return cFetch<createOnetimeResponse>(getCreateOnetimeUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(onetimeEventCreate),
	});
};

export const getCreateOnetimeMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: OnetimeEventCreate }) => {
		return createOnetime(arg, options);
	};
};
export const getCreateOnetimeMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateOnetime`] as const;

export type CreateOnetimeMutationResult = NonNullable<Awaited<ReturnType<typeof createOnetime>>>;

export const useCreateOnetime = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof createOnetime>>,
		TError,
		Key,
		OnetimeEventCreate,
		Awaited<ReturnType<typeof createOnetime>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getCreateOnetimeMutationKey();
	const swrFn = getCreateOnetimeMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type createRecurringResponse200 = {
	data: string;
	status: 200;
};

export type createRecurringResponseSuccess = createRecurringResponse200 & {
	headers: Headers;
};

export type createRecurringResponse = createRecurringResponseSuccess;

export const getCreateRecurringUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateRecurring`;
};

export const createRecurring = async (recurringEventCreate: RecurringEventCreate, options?: RequestInit): Promise<createRecurringResponse> => {
	return cFetch<createRecurringResponse>(getCreateRecurringUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(recurringEventCreate),
	});
};

export const getCreateRecurringMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: RecurringEventCreate }) => {
		return createRecurring(arg, options);
	};
};
export const getCreateRecurringMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateRecurring`] as const;

export type CreateRecurringMutationResult = NonNullable<Awaited<ReturnType<typeof createRecurring>>>;

export const useCreateRecurring = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<
		Awaited<ReturnType<typeof createRecurring>>,
		TError,
		Key,
		RecurringEventCreate,
		Awaited<ReturnType<typeof createRecurring>>
	> & { swrKey?: string };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getCreateRecurringMutationKey();
	const swrFn = getCreateRecurringMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type updateEventResponse200 = {
	data: void;
	status: 200;
};

export type updateEventResponseSuccess = updateEventResponse200 & {
	headers: Headers;
};

export type updateEventResponse = updateEventResponseSuccess;

export const getUpdateEventUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Update`;
};

export const updateEvent = async (options?: RequestInit): Promise<updateEventResponse> => {
	return cFetch<updateEventResponse>(getUpdateEventUrl(), {
		...options,
		method: "POST",
	});
};

export const getUpdateEventMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return updateEvent(options);
	};
};
export const getUpdateEventMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/Update`] as const;

export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>;

export const useUpdateEvent = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<Awaited<ReturnType<typeof updateEvent>>, TError, Key, Arguments, Awaited<ReturnType<typeof updateEvent>>> & {
		swrKey?: string;
	};
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getUpdateEventMutationKey();
	const swrFn = getUpdateEventMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type deleteEventResponse200 = {
	data: void;
	status: 200;
};

export type deleteEventResponseSuccess = deleteEventResponse200 & {
	headers: Headers;
};

export type deleteEventResponse = deleteEventResponseSuccess;

export const getDeleteEventUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Delete`;
};

export const deleteEvent = async (options?: RequestInit): Promise<deleteEventResponse> => {
	return cFetch<deleteEventResponse>(getDeleteEventUrl(), {
		...options,
		method: "POST",
	});
};

export const getDeleteEventMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return deleteEvent(options);
	};
};
export const getDeleteEventMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Event/Delete`] as const;

export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>;

export const useDeleteEvent = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<Awaited<ReturnType<typeof deleteEvent>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteEvent>>> & {
		swrKey?: string;
	};
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getDeleteEventMutationKey();
	const swrFn = getDeleteEventMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type getOnetimeInstanceStateResponse200 = {
	data: EventInstanceStateGet;
	status: 200;
};

export type getOnetimeInstanceStateResponseSuccess = getOnetimeInstanceStateResponse200 & {
	headers: Headers;
};

export type getOnetimeInstanceStateResponse = getOnetimeInstanceStateResponseSuccess;

export const getGetOnetimeInstanceStateUrl = (eventId: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/GetOnetimeInstanceState/onetime/${eventId}`;
};

export const getOnetimeInstanceState = async (eventId: string, options?: RequestInit): Promise<getOnetimeInstanceStateResponse> => {
	return cFetch<getOnetimeInstanceStateResponse>(getGetOnetimeInstanceStateUrl(eventId), {
		...options,
		method: "GET",
	});
};

export const getGetOnetimeInstanceStateKey = (eventId: string) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetOnetimeInstanceState/onetime/${eventId}`] as const;

export type GetOnetimeInstanceStateQueryResult = NonNullable<Awaited<ReturnType<typeof getOnetimeInstanceState>>>;

export const useGetOnetimeInstanceState = <TError = unknown>(
	eventId: string,
	options?: {
		swr?: SWRConfiguration<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError> & { swrKey?: Key; enabled?: boolean };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!eventId;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetOnetimeInstanceStateKey(eventId) : null));
	const swrFn = () => getOnetimeInstanceState(eventId, requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type getRecurringInstanceStateResponse200 = {
	data: EventInstanceStateGet;
	status: 200;
};

export type getRecurringInstanceStateResponseSuccess = getRecurringInstanceStateResponse200 & {
	headers: Headers;
};

export type getRecurringInstanceStateResponse = getRecurringInstanceStateResponseSuccess;

export const getGetRecurringInstanceStateUrl = (eventId: string, eventOccurence: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/GetRecurringInstanceState/recurring/${eventId}/${eventOccurence}`;
};

export const getRecurringInstanceState = async (
	eventId: string,
	eventOccurence: string,
	options?: RequestInit,
): Promise<getRecurringInstanceStateResponse> => {
	return cFetch<getRecurringInstanceStateResponse>(getGetRecurringInstanceStateUrl(eventId, eventOccurence), {
		...options,
		method: "GET",
	});
};

export const getGetRecurringInstanceStateKey = (eventId: string, eventOccurence: string) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetRecurringInstanceState/recurring/${eventId}/${eventOccurence}`] as const;

export type GetRecurringInstanceStateQueryResult = NonNullable<Awaited<ReturnType<typeof getRecurringInstanceState>>>;

export const useGetRecurringInstanceState = <TError = unknown>(
	eventId: string,
	eventOccurence: string,
	options?: {
		swr?: SWRConfiguration<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError> & { swrKey?: Key; enabled?: boolean };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false && !!(eventId && eventOccurence);
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetRecurringInstanceStateKey(eventId, eventOccurence) : null));
	const swrFn = () => getRecurringInstanceState(eventId, eventOccurence, requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type setOnetimeInstanceStateResponse200 = {
	data: void;
	status: 200;
};

export type setOnetimeInstanceStateResponseSuccess = setOnetimeInstanceStateResponse200 & {
	headers: Headers;
};

export type setOnetimeInstanceStateResponse = setOnetimeInstanceStateResponseSuccess;

export const getSetOnetimeInstanceStateUrl = (eventId: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/SetOnetimeInstanceState/onetime/${eventId}`;
};

export const setOnetimeInstanceState = async (
	eventId: string,
	eventInstanceStateSet: EventInstanceStateSet,
	options?: RequestInit,
): Promise<setOnetimeInstanceStateResponse> => {
	return cFetch<setOnetimeInstanceStateResponse>(getSetOnetimeInstanceStateUrl(eventId), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(eventInstanceStateSet),
	});
};

export const getSetOnetimeInstanceStateMutationFetcher = (eventId: string, options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: EventInstanceStateSet }) => {
		return setOnetimeInstanceState(eventId, arg, options);
	};
};
export const getSetOnetimeInstanceStateMutationKey = (eventId: string) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Event/SetOnetimeInstanceState/onetime/${eventId}`] as const;

export type SetOnetimeInstanceStateMutationResult = NonNullable<Awaited<ReturnType<typeof setOnetimeInstanceState>>>;

export const useSetOnetimeInstanceState = <TError = unknown>(
	eventId: string,
	options?: {
		swr?: SWRMutationConfiguration<
			Awaited<ReturnType<typeof setOnetimeInstanceState>>,
			TError,
			Key,
			EventInstanceStateSet,
			Awaited<ReturnType<typeof setOnetimeInstanceState>>
		> & { swrKey?: string };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getSetOnetimeInstanceStateMutationKey(eventId);
	const swrFn = getSetOnetimeInstanceStateMutationFetcher(eventId, requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type setRecurringInstanceStateResponse200 = {
	data: void;
	status: 200;
};

export type setRecurringInstanceStateResponseSuccess = setRecurringInstanceStateResponse200 & {
	headers: Headers;
};

export type setRecurringInstanceStateResponse = setRecurringInstanceStateResponseSuccess;

export const getSetRecurringInstanceStateUrl = (eventId: string, eventOccurence: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/SetRecurringInstanceState/recurring/${eventId}/${eventOccurence}`;
};

export const setRecurringInstanceState = async (
	eventId: string,
	eventOccurence: string,
	eventInstanceStateSet: EventInstanceStateSet,
	options?: RequestInit,
): Promise<setRecurringInstanceStateResponse> => {
	return cFetch<setRecurringInstanceStateResponse>(getSetRecurringInstanceStateUrl(eventId, eventOccurence), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(eventInstanceStateSet),
	});
};

export const getSetRecurringInstanceStateMutationFetcher = (eventId: string, eventOccurence: string, options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: EventInstanceStateSet }) => {
		return setRecurringInstanceState(eventId, eventOccurence, arg, options);
	};
};
export const getSetRecurringInstanceStateMutationKey = (eventId: string, eventOccurence: string) =>
	[`${import.meta.env.VITE_API_ORIGIN}/api/Event/SetRecurringInstanceState/recurring/${eventId}/${eventOccurence}`] as const;

export type SetRecurringInstanceStateMutationResult = NonNullable<Awaited<ReturnType<typeof setRecurringInstanceState>>>;

export const useSetRecurringInstanceState = <TError = unknown>(
	eventId: string,
	eventOccurence: string,
	options?: {
		swr?: SWRMutationConfiguration<
			Awaited<ReturnType<typeof setRecurringInstanceState>>,
			TError,
			Key,
			EventInstanceStateSet,
			Awaited<ReturnType<typeof setRecurringInstanceState>>
		> & { swrKey?: string };
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getSetRecurringInstanceStateMutationKey(eventId, eventOccurence);
	const swrFn = getSetRecurringInstanceStateMutationFetcher(eventId, eventOccurence, requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
