/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	InvalidateOptions,
	MutationFunction,
	MutationFunctionContext,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cFetch } from "../../../other/cfetch";
import type { EventGet, EventInstanceStateGet, EventInstanceStateSet, OnetimeEventCreate, RecurringEventCreate } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

export type listEventsResponse200 = {
	data: EventGet[];
	status: 200;
};

export type listEventsResponseSuccess = listEventsResponse200 & {
	headers: Headers;
};

export type listEventsResponse = listEventsResponseSuccess;

export const getListEventsUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/List`;
};

export const listEvents = async (options?: RequestInit): Promise<listEventsResponse> => {
	return cFetch<listEventsResponse>(getListEventsUrl(), {
		...options,
		method: "GET",
	});
};

export const getListEventsQueryKey = () => {
	return ["listEvents"] as const;
};

export const getListEventsQueryOptions = <TData = Awaited<ReturnType<typeof listEvents>>, TError = unknown>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>>;
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListEventsQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof listEvents>>> = ({ signal }) => listEvents({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type ListEventsQueryResult = NonNullable<Awaited<ReturnType<typeof listEvents>>>;
export type ListEventsQueryError = unknown;

export function useListEvents<TData = Awaited<ReturnType<typeof listEvents>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>> &
			Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof listEvents>>, TError, Awaited<ReturnType<typeof listEvents>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEvents<TData = Awaited<ReturnType<typeof listEvents>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>> &
			Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof listEvents>>, TError, Awaited<ReturnType<typeof listEvents>>>, "initialData">;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListEvents<TData = Awaited<ReturnType<typeof listEvents>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListEvents<TData = Awaited<ReturnType<typeof listEvents>>, TError = unknown>(
	options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listEvents>>, TError, TData>>; request?: SecondParameter<typeof cFetch> },
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getListEventsQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const invalidateListEvents = async (queryClient: QueryClient, options?: InvalidateOptions): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getListEventsQueryKey() }, options);

	return queryClient;
};

export type createOnetimeResponse200 = {
	data: string;
	status: 200;
};

export type createOnetimeResponseSuccess = createOnetimeResponse200 & {
	headers: Headers;
};

export type createOnetimeResponse = createOnetimeResponseSuccess;

export const getCreateOnetimeUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateOnetime`;
};

export const createOnetime = async (onetimeEventCreate: OnetimeEventCreate, options?: RequestInit): Promise<createOnetimeResponse> => {
	return cFetch<createOnetimeResponse>(getCreateOnetimeUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(onetimeEventCreate),
	});
};

export const getCreateOnetimeMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createOnetime>>, TError, { data: OnetimeEventCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof createOnetime>>, TError, { data: OnetimeEventCreate }, TContext> => {
	const mutationKey = ["createOnetime"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOnetime>>, { data: OnetimeEventCreate }> = (props) => {
		const { data } = props ?? {};

		return createOnetime(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof createOnetime>>,
		variables: { data: OnetimeEventCreate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListEventsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type CreateOnetimeMutationResult = NonNullable<Awaited<ReturnType<typeof createOnetime>>>;
export type CreateOnetimeMutationBody = OnetimeEventCreate;
export type CreateOnetimeMutationError = unknown;

export const useCreateOnetime = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createOnetime>>, TError, { data: OnetimeEventCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createOnetime>>, TError, { data: OnetimeEventCreate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getCreateOnetimeMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type createRecurringResponse200 = {
	data: string;
	status: 200;
};

export type createRecurringResponseSuccess = createRecurringResponse200 & {
	headers: Headers;
};

export type createRecurringResponse = createRecurringResponseSuccess;

export const getCreateRecurringUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/CreateRecurring`;
};

export const createRecurring = async (recurringEventCreate: RecurringEventCreate, options?: RequestInit): Promise<createRecurringResponse> => {
	return cFetch<createRecurringResponse>(getCreateRecurringUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(recurringEventCreate),
	});
};

export const getCreateRecurringMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createRecurring>>, TError, { data: RecurringEventCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof createRecurring>>, TError, { data: RecurringEventCreate }, TContext> => {
	const mutationKey = ["createRecurring"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRecurring>>, { data: RecurringEventCreate }> = (props) => {
		const { data } = props ?? {};

		return createRecurring(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof createRecurring>>,
		variables: { data: RecurringEventCreate },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListEventsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type CreateRecurringMutationResult = NonNullable<Awaited<ReturnType<typeof createRecurring>>>;
export type CreateRecurringMutationBody = RecurringEventCreate;
export type CreateRecurringMutationError = unknown;

export const useCreateRecurring = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof createRecurring>>, TError, { data: RecurringEventCreate }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof createRecurring>>, TError, { data: RecurringEventCreate }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getCreateRecurringMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type updateEventResponse200 = {
	data: void;
	status: 200;
};

export type updateEventResponseSuccess = updateEventResponse200 & {
	headers: Headers;
};

export type updateEventResponse = updateEventResponseSuccess;

export const getUpdateEventUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Update`;
};

export const updateEvent = async (options?: RequestInit): Promise<updateEventResponse> => {
	return cFetch<updateEventResponse>(getUpdateEventUrl(), {
		...options,
		method: "POST",
	});
};

export const getUpdateEventMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError, void, TContext> => {
	const mutationKey = ["updateEvent"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEvent>>, void> = () => {
		return updateEvent(requestOptions);
	};

	const onSuccess = (data: Awaited<ReturnType<typeof updateEvent>>, variables: void, onMutateResult: TContext, context: MutationFunctionContext) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListEventsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateEventMutationResult = NonNullable<Awaited<ReturnType<typeof updateEvent>>>;

export type UpdateEventMutationError = unknown;

export const useUpdateEvent = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof updateEvent>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof updateEvent>>, TError, void, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getUpdateEventMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type deleteEventResponse200 = {
	data: void;
	status: 200;
};

export type deleteEventResponseSuccess = deleteEventResponse200 & {
	headers: Headers;
};

export type deleteEventResponse = deleteEventResponseSuccess;

export const getDeleteEventUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/Delete`;
};

export const deleteEvent = async (options?: RequestInit): Promise<deleteEventResponse> => {
	return cFetch<deleteEventResponse>(getDeleteEventUrl(), {
		...options,
		method: "POST",
	});
};

export const getDeleteEventMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError, void, TContext> => {
	const mutationKey = ["deleteEvent"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteEvent>>, void> = () => {
		return deleteEvent(requestOptions);
	};

	const onSuccess = (data: Awaited<ReturnType<typeof deleteEvent>>, variables: void, onMutateResult: TContext, context: MutationFunctionContext) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getListEventsQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type DeleteEventMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEvent>>>;

export type DeleteEventMutationError = unknown;

export const useDeleteEvent = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteEvent>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteEvent>>, TError, void, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getDeleteEventMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type getOnetimeInstanceStateResponse200 = {
	data: EventInstanceStateGet;
	status: 200;
};

export type getOnetimeInstanceStateResponseSuccess = getOnetimeInstanceStateResponse200 & {
	headers: Headers;
};

export type getOnetimeInstanceStateResponse = getOnetimeInstanceStateResponseSuccess;

export const getGetOnetimeInstanceStateUrl = (eventId: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/GetOnetimeInstanceState/onetime/${eventId}`;
};

export const getOnetimeInstanceState = async (eventId: string, options?: RequestInit): Promise<getOnetimeInstanceStateResponse> => {
	return cFetch<getOnetimeInstanceStateResponse>(getGetOnetimeInstanceStateUrl(eventId), {
		...options,
		method: "GET",
	});
};

export const getGetOnetimeInstanceStateQueryKey = (eventId: string) => {
	return ["getOnetimeInstanceState", ...(eventId ? [eventId] : [])] as const;
};

export const getGetOnetimeInstanceStateQueryOptions = <TData = Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError = unknown>(
	eventId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetOnetimeInstanceStateQueryKey(eventId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getOnetimeInstanceState>>> = ({ signal }) =>
		getOnetimeInstanceState(eventId, { signal, ...requestOptions });

	return { queryKey, queryFn, enabled: eventId !== null && eventId !== undefined, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getOnetimeInstanceState>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOnetimeInstanceStateQueryResult = NonNullable<Awaited<ReturnType<typeof getOnetimeInstanceState>>>;
export type GetOnetimeInstanceStateQueryError = unknown;

export function useGetOnetimeInstanceState<TData = Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError = unknown>(
	eventId: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, Awaited<ReturnType<typeof getOnetimeInstanceState>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOnetimeInstanceState<TData = Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError = unknown>(
	eventId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, Awaited<ReturnType<typeof getOnetimeInstanceState>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOnetimeInstanceState<TData = Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError = unknown>(
	eventId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOnetimeInstanceState<TData = Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError = unknown>(
	eventId: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOnetimeInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetOnetimeInstanceStateQueryOptions(eventId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const invalidateGetOnetimeInstanceState = async (
	queryClient: QueryClient,
	eventId: string,
	options?: InvalidateOptions,
): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getGetOnetimeInstanceStateQueryKey(eventId) }, options);

	return queryClient;
};

export type getRecurringInstanceStateResponse200 = {
	data: EventInstanceStateGet;
	status: 200;
};

export type getRecurringInstanceStateResponseSuccess = getRecurringInstanceStateResponse200 & {
	headers: Headers;
};

export type getRecurringInstanceStateResponse = getRecurringInstanceStateResponseSuccess;

export const getGetRecurringInstanceStateUrl = (eventId: string, eventOccurrence: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/GetRecurringInstanceState/recurring/${eventId}/${eventOccurrence}`;
};

export const getRecurringInstanceState = async (
	eventId: string,
	eventOccurrence: string,
	options?: RequestInit,
): Promise<getRecurringInstanceStateResponse> => {
	return cFetch<getRecurringInstanceStateResponse>(getGetRecurringInstanceStateUrl(eventId, eventOccurrence), {
		...options,
		method: "GET",
	});
};

export const getGetRecurringInstanceStateQueryKey = (eventId: string, eventOccurrence: string) => {
	return ["getRecurringInstanceState", ...(eventOccurrence ? [eventOccurrence] : []), ...(eventId ? [eventId] : [])] as const;
};

export const getGetRecurringInstanceStateQueryOptions = <TData = Awaited<ReturnType<typeof getRecurringInstanceState>>, TError = unknown>(
	eventId: string,
	eventOccurrence: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetRecurringInstanceStateQueryKey(eventId, eventOccurrence);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecurringInstanceState>>> = ({ signal }) =>
		getRecurringInstanceState(eventId, eventOccurrence, { signal, ...requestOptions });

	return {
		queryKey,
		queryFn,
		enabled: eventId !== null && eventId !== undefined && eventOccurrence !== null && eventOccurrence !== undefined,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecurringInstanceStateQueryResult = NonNullable<Awaited<ReturnType<typeof getRecurringInstanceState>>>;
export type GetRecurringInstanceStateQueryError = unknown;

export function useGetRecurringInstanceState<TData = Awaited<ReturnType<typeof getRecurringInstanceState>>, TError = unknown>(
	eventId: string,
	eventOccurrence: string,
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRecurringInstanceState>>,
					TError,
					Awaited<ReturnType<typeof getRecurringInstanceState>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecurringInstanceState<TData = Awaited<ReturnType<typeof getRecurringInstanceState>>, TError = unknown>(
	eventId: string,
	eventOccurrence: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getRecurringInstanceState>>,
					TError,
					Awaited<ReturnType<typeof getRecurringInstanceState>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetRecurringInstanceState<TData = Awaited<ReturnType<typeof getRecurringInstanceState>>, TError = unknown>(
	eventId: string,
	eventOccurrence: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetRecurringInstanceState<TData = Awaited<ReturnType<typeof getRecurringInstanceState>>, TError = unknown>(
	eventId: string,
	eventOccurrence: string,
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRecurringInstanceState>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getGetRecurringInstanceStateQueryOptions(eventId, eventOccurrence, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

export const invalidateGetRecurringInstanceState = async (
	queryClient: QueryClient,
	eventId: string,
	eventOccurrence: string,
	options?: InvalidateOptions,
): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getGetRecurringInstanceStateQueryKey(eventId, eventOccurrence) }, options);

	return queryClient;
};

export type setOnetimeInstanceStateResponse200 = {
	data: void;
	status: 200;
};

export type setOnetimeInstanceStateResponseSuccess = setOnetimeInstanceStateResponse200 & {
	headers: Headers;
};

export type setOnetimeInstanceStateResponse = setOnetimeInstanceStateResponseSuccess;

export const getSetOnetimeInstanceStateUrl = (eventId: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/SetOnetimeInstanceState/onetime/${eventId}`;
};

export const setOnetimeInstanceState = async (
	eventId: string,
	eventInstanceStateSet: EventInstanceStateSet,
	options?: RequestInit,
): Promise<setOnetimeInstanceStateResponse> => {
	return cFetch<setOnetimeInstanceStateResponse>(getSetOnetimeInstanceStateUrl(eventId), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(eventInstanceStateSet),
	});
};

export const getSetOnetimeInstanceStateMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setOnetimeInstanceState>>,
			TError,
			{ eventId: string; data: EventInstanceStateSet },
			TContext
		>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof setOnetimeInstanceState>>, TError, { eventId: string; data: EventInstanceStateSet }, TContext> => {
	const mutationKey = ["setOnetimeInstanceState"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof setOnetimeInstanceState>>, { eventId: string; data: EventInstanceStateSet }> = (
		props,
	) => {
		const { eventId, data } = props ?? {};

		return setOnetimeInstanceState(eventId, data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof setOnetimeInstanceState>>,
		variables: { eventId: string; data: EventInstanceStateSet },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({
				predicate: (query) =>
					typeof query.queryKey[0] === "string" &&
					query.queryKey[0].startsWith(`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetOnetimeInstanceState/onetime/`),
			});
			queryClient.invalidateQueries({
				predicate: (query) =>
					typeof query.queryKey[0] === "string" &&
					query.queryKey[0].startsWith(`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetRecurringInstanceState/recurring/`),
			});
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type SetOnetimeInstanceStateMutationResult = NonNullable<Awaited<ReturnType<typeof setOnetimeInstanceState>>>;
export type SetOnetimeInstanceStateMutationBody = EventInstanceStateSet;
export type SetOnetimeInstanceStateMutationError = unknown;

export const useSetOnetimeInstanceState = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setOnetimeInstanceState>>,
			TError,
			{ eventId: string; data: EventInstanceStateSet },
			TContext
		>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof setOnetimeInstanceState>>, TError, { eventId: string; data: EventInstanceStateSet }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getSetOnetimeInstanceStateMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type setRecurringInstanceStateResponse200 = {
	data: void;
	status: 200;
};

export type setRecurringInstanceStateResponseSuccess = setRecurringInstanceStateResponse200 & {
	headers: Headers;
};

export type setRecurringInstanceStateResponse = setRecurringInstanceStateResponseSuccess;

export const getSetRecurringInstanceStateUrl = (eventId: string, eventOccurrence: string) => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Event/SetRecurringInstanceState/recurring/${eventId}/${eventOccurrence}`;
};

export const setRecurringInstanceState = async (
	eventId: string,
	eventOccurrence: string,
	eventInstanceStateSet: EventInstanceStateSet,
	options?: RequestInit,
): Promise<setRecurringInstanceStateResponse> => {
	return cFetch<setRecurringInstanceStateResponse>(getSetRecurringInstanceStateUrl(eventId, eventOccurrence), {
		...options,
		method: "PUT",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(eventInstanceStateSet),
	});
};

export const getSetRecurringInstanceStateMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setRecurringInstanceState>>,
			TError,
			{ eventId: string; eventOccurrence: string; data: EventInstanceStateSet },
			TContext
		>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<
	Awaited<ReturnType<typeof setRecurringInstanceState>>,
	TError,
	{ eventId: string; eventOccurrence: string; data: EventInstanceStateSet },
	TContext
> => {
	const mutationKey = ["setRecurringInstanceState"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof setRecurringInstanceState>>,
		{ eventId: string; eventOccurrence: string; data: EventInstanceStateSet }
	> = (props) => {
		const { eventId, eventOccurrence, data } = props ?? {};

		return setRecurringInstanceState(eventId, eventOccurrence, data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof setRecurringInstanceState>>,
		variables: { eventId: string; eventOccurrence: string; data: EventInstanceStateSet },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({
				predicate: (query) =>
					typeof query.queryKey[0] === "string" &&
					query.queryKey[0].startsWith(`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetOnetimeInstanceState/onetime/`),
			});
			queryClient.invalidateQueries({
				predicate: (query) =>
					typeof query.queryKey[0] === "string" &&
					query.queryKey[0].startsWith(`${import.meta.env.VITE_API_ORIGIN}/api/Event/GetRecurringInstanceState/recurring/`),
			});
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type SetRecurringInstanceStateMutationResult = NonNullable<Awaited<ReturnType<typeof setRecurringInstanceState>>>;
export type SetRecurringInstanceStateMutationBody = EventInstanceStateSet;
export type SetRecurringInstanceStateMutationError = unknown;

export const useSetRecurringInstanceState = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof setRecurringInstanceState>>,
			TError,
			{ eventId: string; eventOccurrence: string; data: EventInstanceStateSet },
			TContext
		>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof setRecurringInstanceState>>,
	TError,
	{ eventId: string; eventOccurrence: string; data: EventInstanceStateSet },
	TContext
> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getSetRecurringInstanceStateMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
