/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EventState } from './eventState';

export interface EventInstanceStateGet {
  eventState: EventState;
}
