/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type EventGetRecurringEventGetType = (typeof EventGetRecurringEventGetType)[keyof typeof EventGetRecurringEventGetType];

export const EventGetRecurringEventGetType = {
	recurring: "recurring",
} as const;
