/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GoalStats {
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	northStarCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	bearingCount: number | string;
	/** @pattern ^-?(?:0|[1-9]\d*)$ */
	movementCount: number | string;
}
