---

- name: Set up PGDG repository and key
  ansible.builtin.deb822_repository:
    name: postgresql
    types: deb
    uris: https://apt.postgresql.org/pub/repos/apt
    suites: "{{ ansible_distribution_release }}-pgdg"
    components: main
    architectures: "{{ pre_dpkg_arch.stdout }}"
    signed_by: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update repositories
  ansible.builtin.apt:
    update_cache: true

- name: Install Patroni and dependencies
  ansible.builtin.apt:
    name: patroni
    state: present
