/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EventGetRecurringEventGetType } from "./eventGetRecurringEventGetType";
import type { RecurrenceGet } from "./recurrenceGet";

export interface EventGetRecurringEventGet {
	type: EventGetRecurringEventGetType;
	recurrence: RecurrenceGet;
	id: string;
	/** @nullable */
	movementId?: string | null;
	/** @maxLength 200 */
	title: string;
	start: string;
	end: string;
}
