/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type EventState = (typeof EventState)[keyof typeof EventState];

export const EventState = {
	Unknown: "Unknown",
	Incomplete: "Incomplete",
	Complete: "Complete",
} as const;
