/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type EventGetOnetimeEventGetType = (typeof EventGetOnetimeEventGetType)[keyof typeof EventGetOnetimeEventGetType];

export const EventGetOnetimeEventGetType = {
	onetime: "onetime",
} as const;
