/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type GoalImportance = (typeof GoalImportance)[keyof typeof GoalImportance];

export const GoalImportance = {
	None: "None",
	High: "High",
} as const;
