/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type GoalType = (typeof GoalType)[keyof typeof GoalType];

export const GoalType = {
	NorthStar: "NorthStar",
	Bearing: "Bearing",
	Movement: "Movement",
} as const;
