/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type MotivationType = (typeof MotivationType)[keyof typeof MotivationType];

export const MotivationType = {
	Carrot: "Carrot",
	Stick: "Stick",
} as const;
