/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { GoalImportance } from "./goalImportance";

export interface NorthStarUpdate {
	/** @maxLength 200 */
	description: string;
	importance: GoalImportance;
	/** @maxLength 5000 */
	justification: string;
	/** @maxLength 200 */
	name: string;
}
