/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export type RecurrenceTypes = (typeof RecurrenceTypes)[keyof typeof RecurrenceTypes];

export const RecurrenceTypes = {
	DAILY: "DAILY",
	WEEKLY: "WEEKLY",
	MONTHLY: "MONTHLY",
	YEARLY: "YEARLY",
} as const;
