/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EventSummary } from "./eventSummary";

export interface ReflectionGet {
	id: string;
	event?: null | EventSummary;
	date: string;
	positive: string[];
	negative: string[];
	improvement: string[];
}
