/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ReflectionCreate {
	/** @nullable */
	eventId?: string | null;
	/** @maxItems 20 */
	positive: string[];
	/** @maxItems 20 */
	negative: string[];
	/** @maxItems 20 */
	improvement: string[];
}
