/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SignupForm {
	/**
	 * @minLength 3
	 * @maxLength 20
	 * @pattern ^[a-zA-Z0-9]+$
	 */
	username: string;
	/** @maxLength 256 */
	email: string;
	/**
	 * @minLength 16
	 * @maxLength 64
	 * @pattern ^[a-zA-Z0-9]+$
	 */
	password: string;
	termsOfService: boolean;
}
