/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetApiReflectionGetParams,
  PostApiReflectionDeleteParams,
  ReflectionCreate,
  ReflectionGet
} from '../../models';






export type getApiReflectionGetResponse200 = {
  data: ReflectionGet
  status: 200
}

export type getApiReflectionGetResponseSuccess = (getApiReflectionGetResponse200) & {
  headers: Headers;
};
;

export type getApiReflectionGetResponse = (getApiReflectionGetResponseSuccess)

export const getGetApiReflectionGetUrl = (params?: GetApiReflectionGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get?${stringifiedParams}` : `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`
}

export const getApiReflectionGet = async (params?: GetApiReflectionGetParams, options?: RequestInit): Promise<getApiReflectionGetResponse> => {

  const res = await fetch(getGetApiReflectionGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiReflectionGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiReflectionGetResponse
}




export const getGetApiReflectionGetKey = (params?: GetApiReflectionGetParams,) => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Get`, ...(params ? [params]: [])] as const;

export type GetApiReflectionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReflectionGet>>>

export const useGetApiReflectionGet = <TError = Promise<unknown>>(
  params?: GetApiReflectionGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiReflectionGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiReflectionGetKey(params) : null);
  const swrFn = () => getApiReflectionGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type getApiReflectionListResponse200 = {
  data: ReflectionGet[]
  status: 200
}

export type getApiReflectionListResponseSuccess = (getApiReflectionListResponse200) & {
  headers: Headers;
};
;

export type getApiReflectionListResponse = (getApiReflectionListResponseSuccess)

export const getGetApiReflectionListUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`
}

export const getApiReflectionList = async ( options?: RequestInit): Promise<getApiReflectionListResponse> => {

  const res = await fetch(getGetApiReflectionListUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiReflectionListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiReflectionListResponse
}




export const getGetApiReflectionListKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/List`] as const;

export type GetApiReflectionListQueryResult = NonNullable<Awaited<ReturnType<typeof getApiReflectionList>>>

export const useGetApiReflectionList = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getApiReflectionList>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetApiReflectionListKey() : null);
  const swrFn = () => getApiReflectionList(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiReflectionCreateResponse200 = {
  data: string
  status: 200
}

export type postApiReflectionCreateResponseSuccess = (postApiReflectionCreateResponse200) & {
  headers: Headers;
};
;

export type postApiReflectionCreateResponse = (postApiReflectionCreateResponseSuccess)

export const getPostApiReflectionCreateUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Create`
}

export const postApiReflectionCreate = async (reflectionCreate: ReflectionCreate, options?: RequestInit): Promise<postApiReflectionCreateResponse> => {

  const res = await fetch(getPostApiReflectionCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reflectionCreate,)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiReflectionCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiReflectionCreateResponse
}




export const getPostApiReflectionCreateMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: ReflectionCreate }) => {
    return postApiReflectionCreate(arg, options);
  }
}
export const getPostApiReflectionCreateMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Create`] as const;

export type PostApiReflectionCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReflectionCreate>>>

export const usePostApiReflectionCreate = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiReflectionCreate>>, TError, Key, ReflectionCreate, Awaited<ReturnType<typeof postApiReflectionCreate>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiReflectionCreateMutationKey();
  const swrFn = getPostApiReflectionCreateMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiReflectionUpdateResponse200 = {
  data: void
  status: 200
}

export type postApiReflectionUpdateResponseSuccess = (postApiReflectionUpdateResponse200) & {
  headers: Headers;
};
;

export type postApiReflectionUpdateResponse = (postApiReflectionUpdateResponseSuccess)

export const getPostApiReflectionUpdateUrl = () => {




  return `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Update`
}

export const postApiReflectionUpdate = async ( options?: RequestInit): Promise<postApiReflectionUpdateResponse> => {

  const res = await fetch(getPostApiReflectionUpdateUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiReflectionUpdateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiReflectionUpdateResponse
}




export const getPostApiReflectionUpdateMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiReflectionUpdate(options);
  }
}
export const getPostApiReflectionUpdateMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Update`] as const;

export type PostApiReflectionUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReflectionUpdate>>>

export const usePostApiReflectionUpdate = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiReflectionUpdate>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiReflectionUpdate>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiReflectionUpdateMutationKey();
  const swrFn = getPostApiReflectionUpdateMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
export type postApiReflectionDeleteResponse200 = {
  data: void
  status: 200
}

export type postApiReflectionDeleteResponseSuccess = (postApiReflectionDeleteResponse200) & {
  headers: Headers;
};
;

export type postApiReflectionDeleteResponse = (postApiReflectionDeleteResponseSuccess)

export const getPostApiReflectionDeleteUrl = (params?: PostApiReflectionDeleteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete?${stringifiedParams}` : `${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete`
}

export const postApiReflectionDelete = async (params?: PostApiReflectionDeleteParams, options?: RequestInit): Promise<postApiReflectionDeleteResponse> => {

  const res = await fetch(getPostApiReflectionDeleteUrl(params),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiReflectionDeleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postApiReflectionDeleteResponse
}




export const getPostApiReflectionDeleteMutationFetcher = (params?: PostApiReflectionDeleteParams, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiReflectionDelete(params, options);
  }
}
export const getPostApiReflectionDeleteMutationKey = (params?: PostApiReflectionDeleteParams,) => [`${import.meta.env.VITE_API_ORIGIN}/api/Reflection/Delete`, ...(params ? [params]: [])] as const;

export type PostApiReflectionDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof postApiReflectionDelete>>>

export const usePostApiReflectionDelete = <TError = Promise<unknown>>(
  params?: PostApiReflectionDeleteParams, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof postApiReflectionDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof postApiReflectionDelete>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getPostApiReflectionDeleteMutationKey(params);
  const swrFn = getPostApiReflectionDeleteMutationFetcher(params, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
