---

- name: Deploy to database
  become: true
  hosts: database
  vars_files:
    - ./vars/database.yaml
  roles:
    - pre
    - sshd
    - accounts
    - ufw
    - fail2ban
    - postgresql
    - etcd
    - patroni
