---

- name: Deploy to backend at runtime
  become: true
  hosts: backend
  vars_files:
    - ../shared/database.yaml
    - ../shared/network.yaml
  roles:
    - ufw_runtime
    - certs_runtime
    - backend_runtime
