---

- name: Deploy to database at runtime
  become: true
  hosts: database
  vars_files:
    - ../shared/network.yaml
  roles:
    - ufw_runtime
    - pki_runtime
    - etcd_runtime
    - patroni_runtime
