---

certs_runtime_crt_source_dir: ~/.data
certs_runtime_crt_target_dir: /etc/app
certs_runtime_root_crt_name: root
certs_runtime_ansible_crt_name: ansible
certs_runtime_chain_crt_name: chain
certs_runtime_system_trust_dir: /usr/local/share/ca-certificates
certs_runtime_app_trust_name: app
certs_runtime_public_crt_dir: public
certs_runtime_private_key_dir: private
