---

- name: Run frontend container
  community.docker.docker_container:
    name: frontend
    image: "{{ frontend_runtime_image }}"
    published_ports:
      - 3080:8080
    restart_policy: always
    state: started
  no_log: true
