/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { cFetch } from "../../../other/cfetch";
import type { SigninForm, SignupForm } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type signUpResponse200 = {
	data: string;
	status: 200;
};

export type signUpResponseSuccess = signUpResponse200 & {
	headers: Headers;
};

export type signUpResponse = signUpResponseSuccess;

export const getSignUpUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`;
};

export const signUp = async (signupForm: SignupForm, options?: RequestInit): Promise<signUpResponse> => {
	return cFetch<signUpResponse>(getSignUpUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signupForm),
	});
};

export const getSignUpMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: SignupForm }) => {
		return signUp(arg, options);
	};
};
export const getSignUpMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`] as const;

export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>;

export const useSignUp = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<Awaited<ReturnType<typeof signUp>>, TError, Key, SignupForm, Awaited<ReturnType<typeof signUp>>> & {
		swrKey?: string;
	};
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getSignUpMutationKey();
	const swrFn = getSignUpMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type signInResponse200 = {
	data: string;
	status: 200;
};

export type signInResponseSuccess = signInResponse200 & {
	headers: Headers;
};

export type signInResponse = signInResponseSuccess;

export const getSignInUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`;
};

export const signIn = async (signinForm: SigninForm, options?: RequestInit): Promise<signInResponse> => {
	return cFetch<signInResponse>(getSignInUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signinForm),
	});
};

export const getSignInMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, { arg }: { arg: SigninForm }) => {
		return signIn(arg, options);
	};
};
export const getSignInMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`] as const;

export type SignInMutationResult = NonNullable<Awaited<ReturnType<typeof signIn>>>;

export const useSignIn = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<Awaited<ReturnType<typeof signIn>>, TError, Key, SigninForm, Awaited<ReturnType<typeof signIn>>> & {
		swrKey?: string;
	};
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getSignInMutationKey();
	const swrFn = getSignInMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type signOutResponse204 = {
	data: void;
	status: 204;
};

export type signOutResponseSuccess = signOutResponse204 & {
	headers: Headers;
};

export type signOutResponse = signOutResponseSuccess;

export const getSignOutUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`;
};

export const signOut = async (options?: RequestInit): Promise<signOutResponse> => {
	return cFetch<signOutResponse>(getSignOutUrl(), {
		...options,
		method: "POST",
	});
};

export const getSignOutMutationFetcher = (options?: SecondParameter<typeof cFetch>) => {
	return (_: Key, __: { arg: Arguments }) => {
		return signOut(options);
	};
};
export const getSignOutMutationKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`] as const;

export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>;

export const useSignOut = <TError = unknown>(options?: {
	swr?: SWRMutationConfiguration<Awaited<ReturnType<typeof signOut>>, TError, Key, Arguments, Awaited<ReturnType<typeof signOut>>> & {
		swrKey?: string;
	};
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const swrKey = swrOptions?.swrKey ?? getSignOutMutationKey();
	const swrFn = getSignOutMutationFetcher(requestOptions);

	const query = useSWRMutation(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
export type isAuthenticatedResponse200 = {
	data: string;
	status: 200;
};

export type isAuthenticatedResponseSuccess = isAuthenticatedResponse200 & {
	headers: Headers;
};

export type isAuthenticatedResponse = isAuthenticatedResponseSuccess;

export const getIsAuthenticatedUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`;
};

export const isAuthenticated = async (options?: RequestInit): Promise<isAuthenticatedResponse> => {
	return cFetch<isAuthenticatedResponse>(getIsAuthenticatedUrl(), {
		...options,
		method: "GET",
	});
};

export const getIsAuthenticatedKey = () => [`${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`] as const;

export type IsAuthenticatedQueryResult = NonNullable<Awaited<ReturnType<typeof isAuthenticated>>>;

export const useIsAuthenticated = <TError = unknown>(options?: {
	swr?: SWRConfiguration<Awaited<ReturnType<typeof isAuthenticated>>, TError> & { swrKey?: Key; enabled?: boolean };
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getIsAuthenticatedKey() : null));
	const swrFn = () => isAuthenticated(requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

	return {
		swrKey,
		...query,
	};
};
