/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

export const getSignUpResponseMock = (): string => faker.word.sample();

export const getSignInResponseMock = (): string => faker.word.sample();

export const getIsAuthenticatedResponseMock = (): string => faker.word.sample();
