/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * backend | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	InvalidateOptions,
	MutationFunction,
	MutationFunctionContext,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { cFetch } from "../../../other/cfetch";
import type { SigninForm, SignupForm } from "../../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type signUpResponse200 = {
	data: string;
	status: 200;
};

export type signUpResponseSuccess = signUpResponse200 & {
	headers: Headers;
};

export type signUpResponse = signUpResponseSuccess;

export const getSignUpUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignUp`;
};

export const signUp = async (signupForm: SignupForm, options?: RequestInit): Promise<signUpResponse> => {
	return cFetch<signUpResponse>(getSignUpUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signupForm),
	});
};

export const getSignUpMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, { data: SignupForm }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, { data: SignupForm }, TContext> => {
	const mutationKey = ["signUp"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof signUp>>, { data: SignupForm }> = (props) => {
		const { data } = props ?? {};

		return signUp(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof signUp>>,
		variables: { data: SignupForm },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getSignInQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type SignUpMutationResult = NonNullable<Awaited<ReturnType<typeof signUp>>>;
export type SignUpMutationBody = SignupForm;
export type SignUpMutationError = unknown;

export const useSignUp = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signUp>>, TError, { data: SignupForm }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof signUp>>, TError, { data: SignupForm }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getSignUpMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type signInResponse200 = {
	data: string;
	status: 200;
};

export type signInResponseSuccess = signInResponse200 & {
	headers: Headers;
};

export type signInResponse = signInResponseSuccess;

export const getSignInUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignIn`;
};

export const signIn = async (signinForm: SigninForm, options?: RequestInit): Promise<signInResponse> => {
	return cFetch<signInResponse>(getSignInUrl(), {
		...options,
		method: "POST",
		headers: { "Content-Type": "application/json", ...options?.headers },
		body: JSON.stringify(signinForm),
	});
};

export const getSignInMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError, { data: SigninForm }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError, { data: SigninForm }, TContext> => {
	const mutationKey = ["signIn"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof signIn>>, { data: SigninForm }> = (props) => {
		const { data } = props ?? {};

		return signIn(data, requestOptions);
	};

	const onSuccess = (
		data: Awaited<ReturnType<typeof signIn>>,
		variables: { data: SigninForm },
		onMutateResult: TContext,
		context: MutationFunctionContext,
	) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getIsAuthenticatedQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type SignInMutationResult = NonNullable<Awaited<ReturnType<typeof signIn>>>;
export type SignInMutationBody = SigninForm;
export type SignInMutationError = unknown;

export const useSignIn = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signIn>>, TError, { data: SigninForm }, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof signIn>>, TError, { data: SigninForm }, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getSignInMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type signOutResponse204 = {
	data: void;
	status: 204;
};

export type signOutResponseSuccess = signOutResponse204 & {
	headers: Headers;
};

export type signOutResponse = signOutResponseSuccess;

export const getSignOutUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/SignOut`;
};

export const signOut = async (options?: RequestInit): Promise<signOutResponse> => {
	return cFetch<signOutResponse>(getSignOutUrl(), {
		...options,
		method: "POST",
	});
};

export const getSignOutMutationOptions = <TError = unknown, TContext = unknown>(
	queryClient: QueryClient,
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
): UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError, void, TContext> => {
	const mutationKey = ["signOut"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<Awaited<ReturnType<typeof signOut>>, void> = () => {
		return signOut(requestOptions);
	};

	const onSuccess = (data: Awaited<ReturnType<typeof signOut>>, variables: void, onMutateResult: TContext, context: MutationFunctionContext) => {
		if (!options?.skipInvalidation) {
			queryClient.invalidateQueries({ queryKey: getIsAuthenticatedQueryKey() });
		}
		mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
	};

	return { ...mutationOptions, mutationFn, onSuccess };
};

export type SignOutMutationResult = NonNullable<Awaited<ReturnType<typeof signOut>>>;

export type SignOutMutationError = unknown;

export const useSignOut = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<Awaited<ReturnType<typeof signOut>>, TError, void, TContext>;
		skipInvalidation?: boolean;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof signOut>>, TError, void, TContext> => {
	const backupQueryClient = useQueryClient();
	return useMutation(getSignOutMutationOptions(queryClient ?? backupQueryClient, options), queryClient);
};
export type isAuthenticatedResponse200 = {
	data: string;
	status: 200;
};

export type isAuthenticatedResponseSuccess = isAuthenticatedResponse200 & {
	headers: Headers;
};

export type isAuthenticatedResponse = isAuthenticatedResponseSuccess;

export const getIsAuthenticatedUrl = () => {
	return `${import.meta.env.VITE_API_ORIGIN}/api/Auth/IsAuthenticated`;
};

export const isAuthenticated = async (options?: RequestInit): Promise<isAuthenticatedResponse> => {
	return cFetch<isAuthenticatedResponse>(getIsAuthenticatedUrl(), {
		...options,
		method: "GET",
	});
};

export const getIsAuthenticatedQueryKey = () => {
	return ["isAuthenticated"] as const;
};

export const getIsAuthenticatedQueryOptions = <TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = unknown>(options?: {
	query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>>;
	request?: SecondParameter<typeof cFetch>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getIsAuthenticatedQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof isAuthenticated>>> = ({ signal }) => isAuthenticated({ signal, ...requestOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type IsAuthenticatedQueryResult = NonNullable<Awaited<ReturnType<typeof isAuthenticated>>>;
export type IsAuthenticatedQueryError = unknown;

export function useIsAuthenticated<TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = unknown>(
	options: {
		query: Partial<UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>> &
			Pick<
				DefinedInitialDataOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, Awaited<ReturnType<typeof isAuthenticated>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIsAuthenticated<TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>> &
			Pick<
				UndefinedInitialDataOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, Awaited<ReturnType<typeof isAuthenticated>>>,
				"initialData"
			>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIsAuthenticated<TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useIsAuthenticated<TData = Awaited<ReturnType<typeof isAuthenticated>>, TError = unknown>(
	options?: {
		query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof isAuthenticated>>, TError, TData>>;
		request?: SecondParameter<typeof cFetch>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
	const queryOptions = getIsAuthenticatedQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}

export const invalidateIsAuthenticated = async (queryClient: QueryClient, options?: InvalidateOptions): Promise<QueryClient> => {
	await queryClient.invalidateQueries({ queryKey: getIsAuthenticatedQueryKey() }, options);

	return queryClient;
};
