---

- name: Create certificate directories
  ansible.builtin.file:
    path: "{{ certs_runtime_crt_target_dir }}/{{ item.name }}"
    state: directory
    owner: root
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - name: "{{ certs_runtime_public_crt_dir }}"
      group: root
      mode: "0755"
    - name: "{{ certs_runtime_private_key_dir }}"
      group: "{{ certs_runtime_group }}"
      mode: "0750"

- name: Install certificates
  ansible.builtin.copy:
    src: "{{ certs_runtime_crt_source_dir }}/{{ item }}.crt"
    dest: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_public_crt_dir }}/{{ item }}.crt"
    owner: root
    group: root
    mode: "0644"
  loop:
    - "{{ certs_runtime_root_crt_name }}"
    - "{{ certs_runtime_ansible_crt_name }}"
    - "{{ certs_runtime_chain_crt_name }}"

- name: Create CA trust directory
  ansible.builtin.file:
    path: "{{ certs_runtime_system_trust_dir }}/{{ certs_runtime_app_trust_name }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install root CA into system trust store
  ansible.builtin.copy:
    src: "{{ certs_runtime_crt_source_dir }}/{{ certs_runtime_root_crt_name }}.crt"
    dest: "{{ certs_runtime_system_trust_dir }}/{{ certs_runtime_app_trust_name }}/{{ certs_runtime_root_crt_name }}.crt"
    owner: root
    group: root
    mode: "0644"
  notify: Update system trust store

- name: Generate service certificate
  ansible.builtin.import_tasks: service_cert.yaml
  when: service_cert is defined
