---

- name: Create service private key
  community.crypto.openssl_privatekey:
    path: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_private_key_dir }}/{{ service_name }}.key"
    type: RSA
    size: 2048
    owner: root
    group: "{{ certs_runtime_group }}"
    mode: "0640"

- name: Create service CSR
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_private_key_dir }}/{{ service_name }}.key"
    common_name: "{{ certs_runtime_common_name }}"
    subject_alt_name: "{{ certs_runtime_sans }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage: "{{ certs_runtime_extended_key_usage }}"
    basic_constraints:
      - "CA:FALSE"
    basic_constraints_critical: true
  register: csr

- name: Get existing certificate contents
  ansible.builtin.slurp:
    src: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_public_crt_dir }}/{{ service_name }}.crt"
  register: service_crt_content

- name: Sign service certificate with Ansible CA
  community.crypto.x509_certificate_pipe:
    content: "{{ service_crt_content.content | b64decode }}"
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ certs_runtime_crt_source_dir }}/{{ certs_runtime_ansible_crt_name }}.crt"
    ownca_privatekey_path: "{{ certs_runtime_crt_source_dir }}/{{ certs_runtime_ansible_crt_name }}.key"
    ownca_not_before: "-1d"
    ownca_not_after: "+365d"
  delegate_to: localhost
  register: signed_service_crt

- name: Install service certificate
  ansible.builtin.copy:
    content: "{{ signed_service_crt.certificate }}"
    dest: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_public_crt_dir }}/{{ service_name }}.crt"
    owner: root
    group: root
    mode: "0644"

# - name: Install service fullchain certificate
#   ansible.builtin.copy:
#     content: "{{ signed_service_crt.csr }}"
#     dest: "{{ certs_runtime_crt_target_dir }}/{{ certs_runtime_public_crt_dir }}/{{ service_name }}-{{ chain_crt_name }}.crt"
#     owner: root
#     group: root
#     mode: "0644"
