---

pki_root_crt_name: root
pki_ansible_crt_name: ansible
pki_chain_crt_name: chain
pki_app_name: app
pki_public_dir_name: public
pki_private_dir_name: private
pki_source_dir: ~/.data
pki_target_dir: /etc/{{ pki_app_name }}
pki_public_dir: "{{ pki_target_dir }}/{{ pki_public_dir_name }}"
pki_private_dir: "{{ pki_target_dir }}/{{ pki_private_dir_name }}"
pki_system_trust_dir: /usr/local/share/ca-certificates
pki_app_trust_dir: "{{ pki_system_trust_dir }}/{{ pki_app_name }}"
