name: packer-deploy
on:
  workflow_dispatch:
jobs:
  validate:
    name: Packer Deploy
    runs-on: ubuntu-24.04
    environment: production
    defaults:
      run:
        working-directory: ./infra/full/packer
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Packer
        uses: hashicorp/setup-packer@c3d53c525d422944e50ee27b840746d6522b08de
        with:
          version: "1.15.3"

      - name: Initialize Packer project
        run: packer init .

      - name: Run Packer Build
        run: packer build .
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DO_API_TOKEN }}
          ANSIBLE_SSH_PUBLIC_KEY: ${{ vars.ANSIBLE_SSH_PUBLIC_KEY }}
          DEV_SSH_PUBLIC_KEY: ${{ vars.DEV_SSH_PUBLIC_KEY }}
