name: packer-validate
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: Packer Validate
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./infra/packer
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Packer
        uses: hashicorp/setup-packer@c3d53c525d422944e50ee27b840746d6522b08de
        with:
          version: "1.15.3"

      - name: Initialize Packer project
        run: packer init .

      - name: Run Packer Validate
        run: packer validate .
